import _, { findWhere } from 'underscore';

export const villages = [
  {
    ids: [{ id: 301 }],
    name: 'Ahlbeck',
    region: 'W',
    slug: 'ahlbeck',
  },
  {
    ids: [{ id: 1 }],
    name: 'Albinshof',
    region: 'A',
    slug: 'albinshof',
  },
  {
    ids: [{ id: 736 }],
    name: 'Alt Brüssow',
    region: 'G',
    slug: 'alt-bruessow',
  },
  {
    ids: [{ id: 2 }],
    name: 'Alt Kosenow',
    region: 'A',
    slug: 'alt-kosenow',
  },
  {
    ids: [{ id: 601 }],
    name: 'Alt Negentin',
    region: 'G',
    slug: 'alt-negentin',
  },
  {
    ids: [{ id: 602 }],
    name: 'Alt Pansow',
    region: 'G',
    slug: 'alt-pansow',
  },
  {
    ids: [{ id: 3 }],
    name: 'Alt Sanitz',
    region: 'A',
    slug: 'alt-sanitz',
  },
  {
    ids: [{ id: 4 }],
    name: 'Alt Teterin',
    region: 'A',
    slug: 'alt-teterin',
  },
  {
    ids: [{ id: 603 }],
    name: 'Alt Ungnade',
    region: 'G',
    slug: 'alt-ungnade',
  },
  {
    ids: [{ id: 5 }],
    name: 'Anklam',
    region: 'A',
    slug: 'anklam',
  },
  {
    ids: [{ id: 138 }],
    name: 'Anklamer Fähre',
    region: 'A',
    slug: 'anklamer-faehre',
  },
  {
    ids: [{ id: 13 }],
    name: 'Auerose',
    region: 'A',
    slug: 'auerose',
  },
  {
    ids: [{ id: 302 }],
    name: 'Balm',
    region: 'W',
    slug: 'balm',
  },
  {
    ids: [{ id: 604 }],
    name: 'Bandelin',
    region: 'G',
    slug: 'bandelin',
  },
  {
    ids: [{ id: 303 }],
    name: 'Bannemin',
    region: 'W',
    slug: 'bannemin',
  },
  {
    ids: [{ id: 304 }],
    name: 'Bansin',
    region: 'W',
    slug: 'bansin',
  },
  {
    ids: [{ id: 305 }],
    name: 'Bansin Dorf',
    region: 'W',
    slug: 'bansin-dorf',
  },
  {
    ids: [{ id: 140 }],
    name: 'Bargischow',
    region: 'A',
    slug: 'bargischow',
  },
  {
    ids: [{ id: 306 }],
    name: 'Bauer',
    region: 'W',
    slug: 'bauer',
  },
  {
    ids: [{ id: 605 }],
    name: 'Behrenhoff',
    region: 'G',
    slug: 'behrenhoff',
  },
  {
    ids: [{ id: 307 }],
    name: 'Benz',
    region: 'W',
    slug: 'benz',
  },
  {
    ids: [{ id: 141 }],
    name: 'Blesewitz',
    region: 'A',
    slug: 'blesewitz',
  },
  {
    ids: [{ id: 142 }],
    name: 'Boldekow',
    region: 'A',
    slug: 'boldekow',
  },
  {
    ids: [{ id: 606 }],
    name: 'Boltenhagen',
    region: 'G',
    slug: 'boltenhagen',
  },
  {
    ids: [{ id: 143 }],
    name: 'Bömitz',
    region: 'A',
    slug: 'boemitz',
  },
  {
    ids: [{ id: 144 }],
    name: 'Borntin',
    region: 'A',
    slug: 'borntin',
  },
  {
    ids: [{ id: 308 }],
    name: 'Bossin',
    region: 'W',
    slug: 'bossin',
  },
  {
    ids: [
      { id: 607, remark: 'außer Peenestr. 8-9a' },
      { id: 734, remark: 'nur Peenestr. 8-9a' },
    ],
    name: 'Breechen',
    region: 'G',
    slug: 'breechen',
  },
  {
    ids: [{ id: 145 }],
    name: 'Brenkenhof',
    region: 'A',
    slug: 'brenkenhof',
  },
  {
    ids: [{ id: 608 }],
    name: 'Brünzow',
    region: 'G',
    slug: 'bruenzow',
  },
  {
    ids: [{ id: 60 }],
    name: 'Brüssow',
    region: 'G',
    slug: 'bruessow',
  },
  {
    ids: [{ id: 30 }],
    name: 'Buddenhagen',
    region: 'W',
    slug: 'buddenhagen',
  },
  {
    ids: [{ id: 146 }],
    name: 'Bugewitz',
    region: 'A',
    slug: 'bugewitz',
  },
  {
    ids: [{ id: 310 }],
    name: 'Buggenhagen',
    region: 'W',
    slug: 'buggenhagen',
  },
  {
    ids: [{ id: 147 }],
    name: 'Buggow',
    region: 'A',
    slug: 'buggow',
  },
  {
    ids: [{ id: 610 }],
    name: 'Busdorf',
    region: 'G',
    slug: 'busdorf',
  },
  {
    ids: [{ id: 148 }],
    name: 'Busow',
    region: 'A',
    slug: 'busow',
  },
  {
    ids: [{ id: 14 }],
    name: 'Butzow',
    region: 'A',
    slug: 'butzow',
  },
  {
    ids: [{ id: 150 }],
    name: 'Charlottenhof',
    region: 'A',
    slug: 'charlottenhof',
  },
  {
    ids: [{ id: 611 }],
    name: 'Dambeck',
    region: 'G',
    slug: 'dambeck',
  },
  {
    ids: [{ id: 612 }],
    name: 'Dargelin',
    region: 'G',
    slug: 'dargelin',
    remark: '+ Dargelin Hof',
  },
  {
    ids: [{ id: 311 }],
    name: 'Dargen',
    region: 'W',
    slug: 'dargen',
  },
  {
    ids: [{ id: 613 }],
    name: 'Dargezin',
    region: 'G',
    slug: 'dargezin',
  },
  {
    ids: [{ id: 614 }],
    name: 'Dargezin Vorwerk',
    region: 'G',
    slug: 'dargezin-vorwerk',
  },
  {
    ids: [{ id: 151 }],
    name: 'Dargibell',
    region: 'A',
    slug: 'dargibell',
  },
  {
    ids: [{ id: 152 }],
    name: 'Daugzin',
    region: 'A',
    slug: 'daugzin',
  },
  {
    ids: [{ id: 153 }],
    name: 'Dennin',
    region: 'A',
    slug: 'dennin',
  },
  {
    ids: [{ id: 615 }],
    name: 'Dersekow',
    region: 'G',
    slug: 'dersekow',
  },
  {
    ids: [{ id: 154 }],
    name: 'Dersewitz',
    region: 'A',
    slug: 'dersewitz',
  },
  {
    ids: [{ id: 312 }],
    name: 'Dewichow',
    region: 'W',
    slug: 'dewichow',
  },
  {
    ids: [{ id: 616 }],
    name: 'Diedrichshagen',
    region: 'G',
    slug: 'diedrichshagen',
  },
  {
    ids: [{ id: 617 }],
    name: 'Dreizehnhausen',
    region: 'G',
    slug: 'dreizehnhausen',
  },
  {
    ids: [{ id: 155 }],
    name: 'Drewelow',
    region: 'A',
    slug: 'drewelow',
  },
  {
    ids: [{ id: 156 }],
    name: 'Ducherow',
    region: 'A',
    slug: 'ducherow',
  },
  {
    ids: [{ id: 157 }],
    name: 'Fasanenhof',
    region: 'A',
    slug: 'fasanenhof',
  },
  {
    ids: [{ id: 618 }],
    name: 'Frätow',
    region: 'G',
    slug: 'fraetow',
  },
  {
    ids: [{ id: 313 }],
    name: 'Freest',
    region: 'W',
    slug: 'freest',
  },
  {
    ids: [{ id: 61 }],
    name: 'Friedrichsfelde',
    region: 'G',
    slug: 'friedrichsfelde',
  },
  {
    ids: [{ id: 620 }],
    name: 'Fritzow',
    region: 'G',
    slug: 'fritzow',
  },
  {
    ids: [{ id: 621 }],
    name: 'Gahlkow',
    region: 'G',
    slug: 'gahlkow',
  },
  {
    ids: [{ id: 314 }],
    name: 'Garz',
    region: 'W',
    slug: 'garz',
  },
  {
    ids: [{ id: 158 }],
    name: 'Gellendin',
    region: 'A',
    slug: 'gellendin',
  },
  {
    ids: [{ id: 315 }],
    name: 'Gellenthin',
    region: 'W',
    slug: 'gellenthin',
  },
  {
    ids: [{ id: 622 }],
    name: 'Giesekenhagen',
    region: 'G',
    slug: 'giesekenhagen',
  },
  {
    ids: [{ id: 623 }],
    name: 'Gladrow',
    region: 'G',
    slug: 'gladrow',
  },
  {
    ids: [{ id: 15 }],
    name: 'Glien ',
    region: 'A',
    slug: 'glien',
  },
  {
    ids: [{ id: 624 }],
    name: 'Glödenhof',
    region: 'G',
    slug: 'gloedenhof',
  },
  {
    ids: [{ id: 316 }],
    name: 'Gneventhin',
    region: 'W',
    slug: 'gneventhin',
  },
  {
    ids: [{ id: 160 }],
    name: 'Gnevezin',
    region: 'A',
    slug: 'gnevezin',
  },
  {
    ids: [{ id: 161 }],
    name: 'Görke, Postlow',
    region: 'A',
    slug: 'goerke-postlow',
  },
  {
    ids: [{ id: 317 }],
    name: 'Görke, Dargen',
    region: 'W',
    slug: 'goerke-dargen',
  },
  {
    ids: [{ id: 318 }],
    name: 'Gothen',
    region: 'W',
    slug: 'gothen',
  },
  {
    ids: [{ id: 162 }],
    name: 'Gramzow',
    region: 'A',
    slug: 'gramzow',
  },
  {
    ids: [{ id: 625 }],
    name: 'Gribow',
    region: 'G',
    slug: 'gribow',
  },
  {
    ids: [{ id: 626 }],
    name: 'Gristow',
    region: 'G',
    slug: 'gristow',
  },
  {
    ids: [{ id: 163 }],
    name: 'Groß Bünzow',
    region: 'A',
    slug: 'gross-buenzow',
  },
  {
    ids: [{ id: 31 }],
    name: 'Groß Ernsthof',
    region: 'W',
    slug: 'gross-ernsthof',
  },
  {
    ids: [{ id: 164 }],
    name: 'Groß Jasedow',
    region: 'A',
    slug: 'gross-jasedow',
  },
  {
    ids: [
      { id: 627, remark: 'außer Dorfstr. 6-6b und 7-11' },
      { id: 731, remark: 'nur Dorfstr. 6-6b und 7-11' },
    ],
    name: 'Groß Karrendorf',
    region: 'G',
    slug: 'gross-karrendorf',
  },
  {
    ids: [{ id: 628 }],
    name: 'Groß Kieshof',
    region: 'G',
    slug: 'gross-kieshof',
  },
  {
    ids: [{ id: 630 }],
    name: 'Groß Kiesow',
    region: 'G',
    slug: 'gross-kiesow',
    remark: '+ Groß Kiesow Meierei',
  },
  {
    ids: [{ id: 631 }],
    name: 'Groß Petershagen',
    region: 'G',
    slug: 'gross-petershagen',
  },
  {
    ids: [{ id: 165 }],
    name: 'Groß Polzin',
    region: 'A',
    slug: 'gross-polzin',
  },
  {
    ids: [{ id: 632 }],
    name: 'Grubenhagen',
    region: 'G',
    slug: 'grubenhagen',
  },
  {
    ids: [{ id: 320 }],
    name: 'Grüssow',
    region: 'W',
    slug: 'gruessow',
  },
  {
    ids: [{ id: 166 }],
    name: 'Grüttow',
    region: 'A',
    slug: 'gruettow',
  },
  {
    ids: [{ id: 633 }],
    name: 'Guest',
    region: 'G',
    slug: 'guest',
  },
  {
    ids: [{ id: 321 }],
    name: 'Gummlin',
    region: 'W',
    slug: 'gummlin',
  },
  {
    ids: [{ id: 634 }],
    name: 'Gustebin',
    region: 'G',
    slug: 'gustebin',
  },
  {
    ids: [
      { id: 635, remark: 'außer Gartenstr., Kleine Wallstr., Müllerwall, Töpferstr.' },
      { id: 735, remark: 'nur Gartenstr., Kleine Wallstr.,Müllerwall, Töpferstr.' },
    ],
    name: 'Gützkow',
    region: 'G',
    slug: 'guetzkow',
  },
  {
    ids: [{ id: 725 }],
    name: 'Gützkow-Meierei',
    region: 'G',
    slug: 'guetzkow-meierei',
  },
  {
    ids: [
      {
        id: 636,
        remark:
          'außer Am Gerstenberg, Hainweg, Obere Bachstraßen, Zum Grund, Zum Hellbusch, Zum Langenmoor',
      },
      {
        id: 727,
        remark:
          'nur Am Gerstenberg, Hainweg, Obere Bachstraßen, Zum Grund, Zum Hellbusch, Zum Langenmoor',
      },
    ],
    name: 'Hanshagen',
    region: 'G',
    slug: 'hanshagen',
  },
  {
    ids: [{ id: 167 }],
    name: 'Heidberg',
    region: 'A',
    slug: 'heidberg',
  },
  {
    ids: [{ id: 637 }],
    name: 'Heilgeisthof',
    region: 'G',
    slug: 'heilgeisthof',
  },
  {
    ids: [{ id: 638 }],
    name: 'Helmshagen',
    region: 'G',
    slug: 'helmshagen',
  },
  {
    ids: [{ id: 322 }],
    name: 'Heringsdorf',
    region: 'W',
    slug: 'heringsdorf',
  },
  {
    ids: [{ id: 324 }],
    name: 'Heringsdorf',
    region: 'W',
    slug: 'heringsdorf-neuhof',
  },
  {
    ids: [{ id: 63 }],
    name: 'Hinrichshagen',
    region: 'G',
    slug: 'hinrichshagen',
    remark: '+ Hof, Buchenberg, Siedlungen',
  },
  {
    ids: [{ id: 326 }],
    name: 'Hohendorf',
    region: 'W',
    slug: 'hohendorf',
  },
  {
    ids: [{ id: 327 }],
    name: 'Hohenfelde',
    region: 'W',
    slug: 'hohenfelde',
  },
  {
    ids: [{ id: 328 }],
    name: 'Hohensee',
    region: 'W',
    slug: 'hohensee',
  },
  {
    ids: [{ id: 32 }],
    name: 'Hollendorf',
    region: 'W',
    slug: 'hollendorf',
  },
  {
    ids: [{ id: 640 }],
    name: 'Immenhorst',
    region: 'G',
    slug: 'immenhorst',
  },
  {
    ids: [{ id: 168 }],
    name: 'Iven',
    region: 'A',
    slug: 'iven',
  },
  {
    ids: [{ id: 641 }],
    name: 'Jagdkrug',
    region: 'G',
    slug: 'jagdkrug',
  },
  {
    ids: [{ id: 642 }],
    name: 'Jägerhof',
    region: 'G',
    slug: 'jaegerhof',
  },
  {
    ids: [{ id: 330 }],
    name: 'Jamitzow',
    region: 'W',
    slug: 'jamitzow',
  },
  {
    ids: [{ id: 16 }],
    name: 'Janow',
    region: 'A',
    slug: 'janow',
  },
  {
    ids: [{ id: 170 }],
    name: 'Japenzin',
    region: 'A',
    slug: 'japenzin',
  },
  {
    ids: [{ id: 171 }],
    name: 'Jargelin',
    region: 'A',
    slug: 'jargelin',
  },
  {
    ids: [{ id: 643 }],
    name: 'Jarmshagen',
    region: 'G',
    slug: 'jarmshagen',
  },
  {
    ids: [{ id: 172 }],
    name: 'Johanneshof',
    region: 'A',
    slug: 'johanneshof',
  },
  {
    ids: [{ id: 644 }],
    name: 'Johannisthal',
    region: 'G',
    slug: 'johannisthal',
  },
  {
    ids: [{ id: 331 }],
    name: 'Kachlin',
    region: 'W',
    slug: 'kachlin',
  },
  {
    ids: [{ id: 173 }],
    name: 'Kagendorf',
    region: 'A',
    slug: 'kagendorf',
  },
  {
    ids: [{ id: 174 }],
    name: 'Kagenow',
    region: 'A',
    slug: 'kagenow',
  },
  {
    ids: [{ id: 175 }],
    name: 'Kalkstein',
    region: 'A',
    slug: 'kalkstein',
  },
  {
    ids: [{ id: 645 }],
    name: 'Kalkvitz',
    region: 'G',
    slug: 'kalkvitz',
  },
  {
    ids: [{ id: 646 }],
    name: 'Kammin',
    region: 'G',
    slug: 'kammin',
  },
  {
    ids: [{ id: 332 }],
    name: 'Kamminke',
    region: 'W',
    slug: 'kamminke',
  },
  {
    ids: [{ id: 176 }],
    name: 'Kamp',
    region: 'A',
    slug: 'kamp',
  },
  {
    ids: [{ id: 647 }],
    name: 'Karbow',
    region: 'G',
    slug: 'karbow',
  },
  {
    ids: [{ id: 648 }],
    name: 'Karlsburg',
    region: 'G',
    slug: 'karlsburg',
  },
  {
    ids: [{ id: 333 }],
    name: 'Karlshagen',
    region: 'W',
    slug: 'karlshagen',
  },
  {
    ids: [{ id: 334 }],
    name: 'Karnin',
    region: 'W',
    slug: 'karnin',
  },
  {
    ids: [{ id: 335 }],
    name: 'Karrin',
    region: 'W',
    slug: 'karrin',
  },
  {
    ids: [{ id: 336 }],
    name: 'Katschow',
    region: 'W',
    slug: 'katschow',
  },
  {
    ids: [{ id: 64 }],
    name: 'Katzow',
    region: 'G',
    slug: 'katzow',
  },
  {
    ids: [{ id: 177 }],
    name: 'Kavelpaß',
    region: 'A',
    slug: 'kavelpass',
  },
  {
    ids: [{ id: 650 }],
    name: 'Kemnitz',
    region: 'G',
    slug: 'kemnitz',
    remark: '+ Kemnitz-Meierei',
  },
  {
    ids: [
      { id: 651, remark: 'außer 11-19' },
      { id: 732, remark: 'nur 11-19' },
    ],
    name: 'Kemnitzerhagen',
    region: 'G',
    slug: 'kemnitzerhagen',
  },
  {
    ids: [{ id: 652 }],
    name: 'Kessin',
    region: 'G',
    slug: 'kessin',
  },
  {
    ids: [{ id: 62 }],
    name: 'Kieshof-Ausbau',
    region: 'G',
    slug: 'kieshof-ausbau',
  },
  {
    ids: [{ id: 178 }],
    name: 'Klein Below',
    region: 'A',
    slug: 'klein-below',
  },
  {
    ids: [{ id: 17 }],
    name: 'Klein Bünzow',
    region: 'A',
    slug: 'klein-buenzow',
  },
  {
    ids: [{ id: 260 }],
    name: 'Klein Bünzow Ausbau',
    region: 'A',
    slug: 'klein-buenzow-ausbau',
  },
  {
    ids: [{ id: 653 }],
    name: 'Klein Ernsthof',
    region: 'G',
    slug: 'klein-ernsthof',
  },
  {
    ids: [{ id: 337 }],
    name: 'Klein Jasedow',
    region: 'W',
    slug: 'klein-jasedow',
  },
  {
    ids: [{ id: 654 }],
    name: 'Klein Karrendorf',
    region: 'G',
    slug: 'klein-karrendorf',
  },
  {
    ids: [{ id: 655 }],
    name: 'Klein Kieshof',
    region: 'G',
    slug: 'klein-kieshof',
  },
  {
    ids: [{ id: 656 }],
    name: 'Klein Kiesow',
    region: 'G',
    slug: 'klein-kiesow',
  },
  {
    ids: [{ id: 657 }],
    name: 'Klein Petershagen',
    region: 'G',
    slug: 'klein-petershagen',
  },
  {
    ids: [{ id: 180 }],
    name: 'Klein Polzin',
    region: 'A',
    slug: 'klein-polzin',
  },
  {
    ids: [{ id: 658 }],
    name: 'Klein Schönwalde',
    region: 'G',
    slug: 'klein-schoenwalde',
  },
  {
    ids: [{ id: 65 }],
    name: 'Klein Zastrow',
    region: 'G',
    slug: 'klein-zastrow',
  },
  {
    ids: [{ id: 181 }],
    name: 'Klitschendorf',
    region: 'A',
    slug: 'klitschendorf',
  },
  {
    ids: [
      { id: 338, remark: 'außer Lindenallee' },
      { id: 543, remark: 'nur Lindenallee' },
    ],
    name: 'Klotzow',
    region: 'W',
    slug: 'klotzow',
  },
  {
    ids: [{ id: 33 }],
    name: 'Kölpin',
    region: 'W',
    slug: 'koelpin',
  },
  {
    ids: [{ id: 340 }],
    name: 'Kölpinsee',
    region: 'W',
    slug: 'koelpinsee',
  },
  {
    ids: [{ id: 660 }],
    name: 'Kölzin',
    region: 'G',
    slug: 'koelzin',
  },
  {
    ids: [{ id: 661 }],
    name: 'Konerow',
    region: 'G',
    slug: 'konerow',
  },
  {
    ids: [{ id: 182 }],
    name: 'Konsages',
    region: 'A',
    slug: 'konsages',
  },
  {
    ids: [{ id: 341 }],
    name: 'Korswandt',
    region: 'W',
    slug: 'korswandt',
  },
  {
    ids: [{ id: 342 }],
    name: 'Koserow',
    region: 'W',
    slug: 'koserow',
  },
  {
    ids: [{ id: 662 }],
    name: 'Kowall',
    region: 'G',
    slug: 'kowall',
  },
  {
    ids: [{ id: 663 }],
    name: 'Kräpelin',
    region: 'G',
    slug: 'kraepelin',
  },
  {
    ids: [{ id: 664 }],
    name: 'Krebsow',
    region: 'G',
    slug: 'krebsow',
  },
  {
    ids: [{ id: 183 }],
    name: 'Krenzow',
    region: 'A',
    slug: 'krenzow',
  },
  {
    ids: [{ id: 184 }],
    name: 'Krien',
    region: 'A',
    slug: 'krien',
  },
  {
    ids: [{ id: 185 }],
    name: 'Krien-Horst',
    region: 'A',
    slug: 'krien-horst',
  },
  {
    ids: [{ id: 343 }],
    name: 'Krienke',
    region: 'W',
    slug: 'krienke',
  },
  {
    ids: [{ id: 344 }],
    name: 'Kröslin',
    region: 'W',
    slug: 'kroeslin',
  },
  {
    ids: [{ id: 345 }],
    name: 'Krummin',
    region: 'W',
    slug: 'krummin',
  },
  {
    ids: [{ id: 186 }],
    name: 'Krusenfelde',
    region: 'A',
    slug: 'krusenfelde',
  },
  {
    ids: [{ id: 187 }],
    name: 'Krusenkrien',
    region: 'A',
    slug: 'krusenkrien',
  },
  {
    ids: [{ id: 665 }],
    name: 'Kühlenhagen',
    region: 'G',
    slug: 'kuehlenhagen',
  },
  {
    ids: [{ id: 666 }],
    name: 'Kuntzow',
    region: 'G',
    slug: 'kuntzow',
  },
  {
    ids: [{ id: 188 }],
    name: 'Kurtshagen',
    region: 'A',
    slug: 'kurtshagen',
  },
  {
    ids: [{ id: 346 }],
    name: 'Kutzow',
    region: 'W',
    slug: 'kutzow',
  },
  {
    ids: [{ id: 347 }],
    name: 'Labömitz',
    region: 'W',
    slug: 'laboemitz',
  },
  {
    ids: [{ id: 348 }],
    name: 'Lassan',
    region: 'W',
    slug: 'lassan',
  },
  {
    ids: [{ id: 667 }],
    name: 'Latzow',
    region: 'G',
    slug: 'latzow',
  },
  {
    ids: [{ id: 668 }],
    name: 'Leist',
    region: 'G',
    slug: 'leist',
  },
  {
    ids: [{ id: 18 }],
    name: 'Lentschow',
    region: 'A',
    slug: 'lentschow',
  },
  {
    ids: [{ id: 66 }],
    name: 'Levenhagen',
    region: 'G',
    slug: 'levenhagen',
  },
  {
    ids: [{ id: 190 }],
    name: 'Libnow',
    region: 'A',
    slug: 'libnow',
  },
  {
    ids: [{ id: 34 }],
    name: 'Liepe',
    region: 'W',
    slug: 'liepe',
  },
  {
    ids: [{ id: 191 }],
    name: 'Liepen',
    region: 'A',
    slug: 'liepen',
  },
  {
    ids: [{ id: 350 }],
    name: 'Loddin',
    region: 'W',
    slug: 'loddin',
  },
  {
    ids: [{ id: 670 }],
    name: 'Lodmannshagen',
    region: 'G',
    slug: 'lodmannshagen',
  },
  {
    ids: [{ id: 671 }],
    name: 'Loissin',
    region: 'G',
    slug: 'loissin',
  },
  {
    ids: [{ id: 192 }],
    name: 'Löwitz',
    region: 'A',
    slug: 'loewitz',
  },
  {
    ids: [{ id: 672 }],
    name: 'Lubmin',
    region: 'G',
    slug: 'lubmin',
  },
  {
    ids: [{ id: 193 }],
    name: 'Lucienhof',
    region: 'A',
    slug: 'lucienhof',
  },
  {
    ids: [{ id: 673 }],
    name: 'Ludwigsburg',
    region: 'G',
    slug: 'ludwigsburg',
  },
  {
    ids: [{ id: 674 }],
    name: 'Lühmannsdorf',
    region: 'G',
    slug: 'luehmannsdorf',
  },
  {
    ids: [{ id: 194 }],
    name: 'Lüskow',
    region: 'A',
    slug: 'lueskow',
  },
  {
    ids: [{ id: 675 }],
    name: 'Lüssow',
    region: 'G',
    slug: 'luessow',
  },
  {
    ids: [{ id: 351 }],
    name: 'Lütow',
    region: 'W',
    slug: 'luetow',
  },
  {
    ids: [{ id: 352 }],
    name: 'Mahlzow',
    region: 'W',
    slug: 'mahlzow',
  },
  {
    ids: [{ id: 195 }],
    name: 'Marienthal',
    region: 'A',
    slug: 'marienthal',
  },
  {
    ids: [{ id: 196 }],
    name: 'Medow',
    region: 'A',
    slug: 'medow',
  },
  {
    ids: [{ id: 353 }],
    name: 'Mellenthin',
    region: 'W',
    slug: 'mellenthin',
  },
  {
    ids: [{ id: 197 }],
    name: 'Menzlin',
    region: 'A',
    slug: 'menzlin',
  },
  {
    ids: [{ id: 676 }],
    name: 'Mesekenhagen',
    region: 'G',
    slug: 'mesekenhagen',
  },
  {
    ids: [{ id: 354 }],
    name: 'Milchhorst',
    region: 'W',
    slug: 'milchhorst',
  },
  {
    ids: [{ id: 677 }],
    name: 'Moeckow',
    region: 'G',
    slug: 'moeckow',
    remark: '+ Moeckow-Berg',
  },
  {
    ids: [{ id: 355 }],
    name: 'Mölschow',
    region: 'W',
    slug: 'moelschow',
  },
  {
    ids: [{ id: 356 }],
    name: 'Mönchow',
    region: 'W',
    slug: 'moenchow',
  },
  {
    ids: [{ id: 357 }],
    name: 'Morgenitz ',
    region: 'W',
    slug: 'morgenitz',
  },
  {
    ids: [{ id: 198 }],
    name: 'Müggenburg',
    region: 'A',
    slug: 'mueggenburg',
  },
  {
    ids: [{ id: 19 }],
    name: 'Murchin',
    region: 'A',
    slug: 'murchin',
  },
  {
    ids: [{ id: 678 }],
    name: 'Müssow',
    region: 'G',
    slug: 'muessow',
  },
  {
    ids: [{ id: 358 }],
    name: 'Neeberg',
    region: 'W',
    slug: 'neeberg',
  },
  {
    ids: [{ id: 200 }],
    name: 'Neetzow',
    region: 'A',
    slug: 'neetzow',
  },
  {
    ids: [{ id: 35 }],
    name: 'Negenmark',
    region: 'W',
    slug: 'negenmark',
  },
  {
    ids: [{ id: 360 }],
    name: 'Neppermin',
    region: 'W',
    slug: 'neppermin',
  },
  {
    ids: [{ id: 67 }],
    name: 'Nepzin',
    region: 'G',
    slug: 'nepzin',
  },
  {
    ids: [{ id: 201 }],
    name: 'Nerdin',
    region: 'A',
    slug: 'nerdin',
  },
  {
    ids: [{ id: 680 }],
    name: 'Netzeband',
    region: 'G',
    slug: 'netzeband',
  },
  {
    ids: [{ id: 361 }],
    name: 'Netzelkow',
    region: 'W',
    slug: 'netzelkow',
  },
  {
    ids: [{ id: 681 }],
    name: 'Neu Boltenhagen',
    region: 'G',
    slug: 'neu-boltenhagen',
  },
  {
    ids: [{ id: 682 }],
    name: 'Neu Dargelin',
    region: 'G',
    slug: 'neu-dargelin',
  },
  {
    ids: [{ id: 202 }],
    name: 'Neu Kosenow',
    region: 'A',
    slug: 'neu-kosenow',
  },
  {
    ids: [{ id: 203 }],
    name: 'Neu Krien',
    region: 'A',
    slug: 'neu-krien',
  },
  {
    ids: [{ id: 683 }],
    name: 'Neu Negentin',
    region: 'G',
    slug: 'neu-negentin',
  },
  {
    ids: [{ id: 684 }],
    name: 'Neu Pansow',
    region: 'G',
    slug: 'neu-pansow',
  },
  {
    ids: [{ id: 362 }],
    name: 'Neu Pudagla',
    region: 'W',
    slug: 'neu-pudagla',
  },
  {
    ids: [{ id: 363 }],
    name: 'Neu Sallenthin',
    region: 'W',
    slug: 'neu-sallenthin',
  },
  {
    ids: [{ id: 204 }],
    name: 'Neu Sanitz',
    region: 'A',
    slug: 'neu-sanitz',
  },
  {
    ids: [{ id: 205 }],
    name: 'Neu Teterin',
    region: 'A',
    slug: 'neu-teterin',
  },
  {
    ids: [{ id: 685 }],
    name: 'Neu Ungnade',
    region: 'G',
    slug: 'neu-ungnade',
  },
  {
    ids: [{ id: 364 }],
    name: 'Neuendorf, Lütow',
    region: 'W',
    slug: 'neuendorf-luetow',
  },
  {
    ids: [{ id: 686 }],
    name: 'Neuendorf, Gützkow',
    region: 'G',
    slug: 'neuendorf-guetzkow',
  },
  {
    ids: [{ id: 687 }],
    name: 'Neuendorf, Kemnitz',
    region: 'G',
    slug: 'neuendorf-kemnitz',
    remark: '+ Neuendorf-Ausbau',
  },
  {
    ids: [{ id: 206 }],
    name: 'Neuendorf A, Ducherow',
    region: 'A',
    slug: 'neuendorf-a-ducherow',
  },
  {
    ids: [{ id: 207 }],
    name: 'Neuendorf B, Spantekow',
    region: 'A',
    slug: 'neuendorf-b-spantekow',
  },
  {
    ids: [{ id: 208 }],
    name: 'Neuenkirchen (bei Anklam)',
    region: 'A',
    slug: 'neuenkirchen-bei-anklam',
  },
  {
    ids: [{ id: 688 }],
    name: 'Neuenkirchen (bei Greifswald)',
    region: 'G',
    slug: 'neuenkirchen-bei-greifswald',
  },
  {
    ids: [{ id: 20 }],
    name: 'Neuhof, Stolpe an der Peene',
    region: 'A',
    slug: 'neuhof-stolpe-an-der-peene',
  },
  {
    ids: [{ id: 365 }],
    name: 'Neverow',
    region: 'W',
    slug: 'neverow',
  },
  {
    ids: [{ id: 68 }],
    name: 'Nonnendorf',
    region: 'G',
    slug: 'nonnendorf',
  },
  {
    ids: [{ id: 690 }],
    name: 'Oldenburg',
    region: 'G',
    slug: 'oldenburg',
  },
  {
    ids: [{ id: 691 }],
    name: 'Oldenhagen',
    region: 'G',
    slug: 'oldenhagen',
  },
  {
    ids: [{ id: 366 }],
    name: 'Ostklüne',
    region: 'W',
    slug: 'ostkluene',
  },
  {
    ids: [{ id: 692 }],
    name: 'Owstin',
    region: 'G',
    slug: 'owstin',
  },
  {
    ids: [{ id: 210 }],
    name: 'Padderow',
    region: 'A',
    slug: 'padderow',
  },
  {
    ids: [{ id: 211 }],
    name: 'Pamitz',
    region: 'A',
    slug: 'pamitz',
  },
  {
    ids: [{ id: 212 }],
    name: 'Panschow',
    region: 'A',
    slug: 'panschow',
  },
  {
    ids: [{ id: 367 }],
    name: 'Papendorf',
    region: 'W',
    slug: 'papendorf',
  },
  {
    ids: [{ id: 368 }],
    name: 'Paske',
    region: 'W',
    slug: 'paske',
  },
  {
    ids: [{ id: 213 }],
    name: 'Pätschow',
    region: 'A',
    slug: 'paetschow',
  },
  {
    ids: [{ id: 36 }],
    name: 'Peenemünde',
    region: 'W',
    slug: 'peenemuende',
  },
  {
    ids: [{ id: 214 }],
    name: 'Pelsin',
    region: 'A',
    slug: 'pelsin',
  },
  {
    ids: [{ id: 693 }],
    name: 'Pentin ',
    region: 'G',
    slug: 'pentin',
  },
  {
    ids: [{ id: 215 }],
    name: 'Pinnow',
    region: 'A',
    slug: 'pinnow',
  },
  {
    ids: [{ id: 216 }],
    name: 'Postlow',
    region: 'A',
    slug: 'postlow',
  },
  {
    ids: [{ id: 694 }],
    name: 'Potthagen',
    region: 'G',
    slug: 'potthagen',
  },
  {
    ids: [{ id: 370 }],
    name: 'Prätenow',
    region: 'W',
    slug: 'praetenow',
  },
  {
    ids: [{ id: 217 }],
    name: 'Preetzen',
    region: 'A',
    slug: 'preetzen',
  },
  {
    ids: [{ id: 218 }],
    name: 'Priemen',
    region: 'A',
    slug: 'priemen',
  },
  {
    ids: [{ id: 371 }],
    name: 'Pritzier',
    region: 'W',
    slug: 'pritzier',
  },
  {
    ids: [{ id: 695 }],
    name: 'Pritzwald',
    region: 'G',
    slug: 'pritzwald',
  },
  {
    ids: [{ id: 372 }],
    name: 'Pudagla',
    region: 'W',
    slug: 'pudagla',
  },
  {
    ids: [{ id: 373 }],
    name: 'Pulow',
    region: 'W',
    slug: 'pulow',
  },
  {
    ids: [{ id: 21 }],
    name: 'Putzar',
    region: 'A',
    slug: 'putzar',
  },
  {
    ids: [{ id: 374 }],
    name: 'Quilitz',
    region: 'W',
    slug: 'quilitz',
  },
  {
    ids: [{ id: 220 }],
    name: 'Quilow',
    region: 'A',
    slug: 'quilow',
  },
  {
    ids: [
      { id: 696, remark: 'außer Am Felde 26-27' },
      { id: 733, remark: 'nur Am Felde 26-27' },
    ],
    name: 'Radlow',
    region: 'G',
    slug: 'radlow',
  },
  {
    ids: [{ id: 221 }],
    name: 'Ramitzow',
    region: 'A',
    slug: 'ramitzow',
  },
  {
    ids: [{ id: 375 }],
    name: 'Rankwitz',
    region: 'W',
    slug: 'rankwitz',
  },
  {
    ids: [{ id: 697 }],
    name: 'Ranzin',
    region: 'G',
    slug: 'ranzin',
  },
  {
    ids: [{ id: 698 }],
    name: 'Rappenhagen',
    region: 'G',
    slug: 'rappenhagen',
  },
  {
    ids: [{ id: 222 }],
    name: 'Rathebur',
    region: 'A',
    slug: 'rathebur',
  },
  {
    ids: [{ id: 223 }],
    name: 'Rebelow',
    region: 'A',
    slug: 'rebelow',
  },
  {
    ids: [{ id: 376 }],
    name: 'Reestow',
    region: 'W',
    slug: 'reestow',
  },
  {
    ids: [{ id: 377 }],
    name: 'Reetzow',
    region: 'W',
    slug: 'reetzow',
  },
  {
    ids: [{ id: 224 }],
    name: 'Rehberg',
    region: 'A',
    slug: 'rehberg',
  },
  {
    ids: [{ id: 225 }],
    name: 'Relzow',
    region: 'A',
    slug: 'relzow',
  },
  {
    ids: [{ id: 226 }],
    name: 'Rosenhagen',
    region: 'A',
    slug: 'rosenhagen',
  },
  {
    ids: [{ id: 227 }],
    name: 'Rossin',
    region: 'A',
    slug: 'rossin',
  },
  {
    ids: [{ id: 228 }],
    name: 'Rubenow, Boldekow',
    region: 'A',
    slug: 'rubenow-boldekow',
  },
  {
    ids: [{ id: 69 }],
    name: 'Rubenow',
    region: 'G',
    slug: 'rubenow',
  },
  {
    ids: [{ id: 22 }],
    name: 'Rubkow',
    region: 'A',
    slug: 'rubkow',
  },
  {
    ids: [{ id: 230 }],
    name: 'Salchow',
    region: 'A',
    slug: 'salchow',
  },
  {
    ids: [{ id: 378 }],
    name: 'Sallenthin',
    region: 'W',
    slug: 'sallenthin',
  },
  {
    ids: [{ id: 700 }],
    name: 'Sanz',
    region: 'G',
    slug: 'sanz',
  },
  {
    ids: [{ id: 231 }],
    name: 'Sarnow',
    region: 'A',
    slug: 'sarnow',
  },
  {
    ids: [{ id: 37 }],
    name: 'Sauzin',
    region: 'W',
    slug: 'sauzin',
  },
  {
    ids: [{ id: 380 }],
    name: 'Schalense',
    region: 'W',
    slug: 'schalense',
  },
  {
    ids: [{ id: 701 }],
    name: 'Schlagtow',
    region: 'G',
    slug: 'schlagtow',
  },
  {
    ids: [{ id: 702 }],
    name: 'Schlagtow-Meierei',
    region: 'G',
    slug: 'schlagtow-meierei',
  },
  {
    ids: [{ id: 232 }],
    name: 'Schlatkow',
    region: 'A',
    slug: 'schlatkow',
  },
  {
    ids: [{ id: 233 }],
    name: 'Schmatzin',
    region: 'A',
    slug: 'schmatzin',
  },
  {
    ids: [{ id: 703 }],
    name: 'Schmoldow',
    region: 'G',
    slug: 'schmoldow',
  },
  {
    ids: [{ id: 234 }],
    name: 'Schmuggerow',
    region: 'A',
    slug: 'schmuggerow',
  },
  {
    ids: [{ id: 235 }],
    name: 'Schwerinsburg',
    region: 'A',
    slug: 'schwerinsburg',
  },
  {
    ids: [{ id: 236 }],
    name: 'Schwerinshorst',
    region: 'A',
    slug: 'schwerinshorst',
  },
  {
    ids: [{ id: 381 }],
    name: 'Seckeritz',
    region: 'W',
    slug: 'seckeritz',
  },
  {
    ids: [{ id: 382 }],
    name: 'Sellin',
    region: 'W',
    slug: 'sellin',
  },
  {
    ids: [{ id: 704 }],
    name: 'Sestelin',
    region: 'G',
    slug: 'sestelin',
  },
  {
    ids: [{ id: 237 }],
    name: 'Sophienhof',
    region: 'A',
    slug: 'sophienhof',
  },
  {
    ids: [{ id: 383 }],
    name: 'Spandowerhagen',
    region: 'W',
    slug: 'spandowerhagen',
  },
  {
    ids: [{ id: 238 }],
    name: 'Spantekow',
    region: 'A',
    slug: 'spantekow',
  },
  {
    ids: [{ id: 384 }],
    name: 'Stagnieß',
    region: 'W',
    slug: 'stagniess',
  },
  {
    ids: [{ id: 23 }],
    name: 'Stammersfelde',
    region: 'A',
    slug: 'stammersfelde',
  },
  {
    ids: [{ id: 705 }],
    name: 'Steffenshagen',
    region: 'G',
    slug: 'steffenshagen',
  },
  {
    ids: [{ id: 706 }],
    name: 'Steinfurth',
    region: 'G',
    slug: 'steinfurth',
  },
  {
    ids: [{ id: 240 }],
    name: 'Steinmocker',
    region: 'A',
    slug: 'steinmocker',
  },
  {
    ids: [{ id: 707 }],
    name: 'Stevelin',
    region: 'G',
    slug: 'stevelin',
  },
  {
    ids: [{ id: 708 }],
    name: 'Stilow',
    region: 'G',
    slug: 'stilow',
  },
  {
    ids: [{ id: 70 }],
    name: 'Stilow-Siedlung',
    region: 'G',
    slug: 'stilow-siedlung',
  },
  {
    ids: [{ id: 385 }],
    name: 'Stoben',
    region: 'W',
    slug: 'stoben',
  },
  {
    ids: [{ id: 241 }],
    name: 'Stolpe an der Peene',
    region: 'A',
    slug: 'stolpe-an-der-peene',
  },
  {
    ids: [{ id: 386 }],
    name: 'Stolpe auf Usedom',
    region: 'W',
    slug: 'stolpe-auf-usedom',
  },
  {
    ids: [{ id: 710 }],
    name: 'Strellin',
    region: 'G',
    slug: 'strellin',
  },
  {
    ids: [{ id: 711 }],
    name: 'Stresow',
    region: 'G',
    slug: 'stresow',
    remark: '+ Stresow-Siedlung',
  },
  {
    ids: [{ id: 242 }],
    name: 'Stretense',
    region: 'A',
    slug: 'stretense',
  },
  {
    ids: [{ id: 243 }],
    name: 'Strippow',
    region: 'A',
    slug: 'strippow',
  },
  {
    ids: [{ id: 387 }],
    name: 'Stubbenfelde',
    region: 'W',
    slug: 'stubbenfelde',
  },
  {
    ids: [{ id: 712 }],
    name: 'Subzow',
    region: 'G',
    slug: 'subzow',
  },
  {
    ids: [{ id: 388 }],
    name: 'Suckow',
    region: 'W',
    slug: 'suckow',
  },
  {
    ids: [{ id: 244 }],
    name: 'Thurow',
    region: 'A',
    slug: 'thurow',
  },
  {
    ids: [{ id: 713 }],
    name: 'Thurow',
    region: 'G',
    slug: 'thurow',
  },
  {
    ids: [{ id: 245 }],
    name: 'Tramstow',
    region: 'A',
    slug: 'tramstow',
  },
  {
    ids: [{ id: 38 }],
    name: 'Trassenheide',
    region: 'W',
    slug: 'trassenheide',
  },
  {
    ids: [{ id: 390 }],
    name: 'Ückeritz',
    region: 'W',
    slug: 'ueckeritz',
  },
  {
    ids: [{ id: 391 }],
    name: 'Ulrichshorst',
    region: 'W',
    slug: 'ulrichshorst',
  },
  {
    ids: [{ id: 714 }],
    name: 'Upatel',
    region: 'G',
    slug: 'upatel',
  },
  {
    ids: [{ id: 392 }],
    name: 'Usedom',
    region: 'W',
    slug: 'usedom',
  },
  {
    ids: [{ id: 715 }],
    name: 'Vargatz',
    region: 'G',
    slug: 'vargatz',
  },
  {
    ids: [{ id: 716 }],
    name: 'Vierow',
    region: 'G',
    slug: 'vierow',
  },
  {
    ids: [{ id: 246 }],
    name: 'Vitense',
    region: 'A',
    slug: 'vitense',
  },
  {
    ids: [{ id: 717 }],
    name: 'Voddow',
    region: 'G',
    slug: 'voddow',
    remark: '+ Nieder-Voddow',
  },
  {
    ids: [{ id: 393 }],
    name: 'Voßberg',
    region: 'W',
    slug: 'vossberg',
  },
  {
    ids: [{ id: 718 }],
    name: 'Wackerow',
    region: 'G',
    slug: 'wackerow',
  },
  {
    ids: [{ id: 247 }],
    name: 'Wahlendow',
    region: 'A',
    slug: 'wahlendow',
  },
  {
    ids: [{ id: 71 }],
    name: 'Wampen',
    region: 'G',
    slug: 'wampen',
  },
  {
    ids: [{ id: 394 }],
    name: 'Wangelkow',
    region: 'W',
    slug: 'wangelkow',
  },
  {
    ids: [{ id: 395 }],
    name: 'Warthe',
    region: 'W',
    slug: 'warthe',
  },
  {
    ids: [{ id: 396 }],
    name: 'Waschow',
    region: 'W',
    slug: 'waschow',
  },
  {
    ids: [{ id: 248 }],
    name: 'Wegezin',
    region: 'A',
    slug: 'wegezin',
  },
  {
    ids: [{ id: 397 }],
    name: 'Wehrland',
    region: 'W',
    slug: 'wehrland',
  },
  {
    ids: [{ id: 398 }],
    name: 'Weiblitz',
    region: 'W',
    slug: 'weiblitz',
  },
  {
    ids: [{ id: 720 }],
    name: 'Weitenhagen',
    region: 'G',
    slug: 'weitenhagen',
  },
  {
    ids: [{ id: 39 }],
    name: 'Welzin',
    region: 'W',
    slug: 'welzin',
  },
  {
    ids: [{ id: 400 }],
    name: 'West-Klüne',
    region: 'W',
    slug: 'west-kluene',
  },
  {
    ids: [{ id: 401 }],
    name: 'Wilhelmsfelde',
    region: 'W',
    slug: 'wilhelmsfelde',
  },
  {
    ids: [{ id: 402 }],
    name: 'Wilhelmshof',
    region: 'W',
    slug: 'wilhelmshof',
  },
  {
    ids: [{ id: 24 }],
    name: 'Wolfradshof',
    region: 'A',
    slug: 'wolfradshof',
  },
  {
    ids: [{ id: 403 }],
    name: 'Wolgast ',
    region: 'W',
    slug: 'wolgast',
  },
  {
    ids: [{ id: 250 }],
    name: 'Woserow',
    region: 'A',
    slug: 'woserow',
  },
  {
    ids: [{ id: 721 }],
    name: 'Wrangelsburg',
    region: 'G',
    slug: 'wrangelsburg',
  },
  {
    ids: [{ id: 251 }],
    name: 'Wusseken',
    region: 'A',
    slug: 'wusseken',
  },
  {
    ids: [{ id: 252 }],
    name: 'Wussentin',
    region: 'A',
    slug: 'wussentin',
  },
  {
    ids: [{ id: 256 }],
    name: 'Wussentin-Ausbau',
    region: 'A',
    slug: 'wussentin-ausbau',
  },
  {
    ids: [{ id: 722 }],
    name: 'Wusterhusen',
    region: 'G',
    slug: 'wusterhusen',
  },
  {
    ids: [{ id: 726 }],
    name: 'Wusterhusen',
    region: 'G',
    slug: 'wusterhusen-neubauten',
  },
  {
    ids: [{ id: 723 }],
    name: 'Zarnekow',
    region: 'G',
    slug: 'zarnekow',
  },
  {
    ids: [{ id: 531 }],
    name: 'Zarnitz',
    region: 'W',
    slug: 'zarnitz',
  },
  {
    ids: [{ id: 253 }],
    name: 'Zarrentin',
    region: 'A',
    slug: 'zarrentin',
  },
  {
    ids: [{ id: 532 }],
    name: 'Zecherin, Usedom',
    region: 'W',
    slug: 'zecherin-usedom',
  },
  {
    ids: [{ id: 533 }],
    name: 'Zecherin, Mölschow',
    region: 'W',
    slug: 'zecherin-moelschow',
  },
  {
    ids: [{ id: 534 }],
    name: 'Zemitz',
    region: 'W',
    slug: 'zemitz',
  },
  {
    ids: [{ id: 535 }],
    name: 'Zempin',
    region: 'W',
    slug: 'zempin',
  },
  {
    ids: [{ id: 536 }],
    name: 'Ziemitz',
    region: 'W',
    slug: 'ziemitz',
  },
  {
    ids: [{ id: 254 }],
    name: 'Ziethen',
    region: 'A',
    slug: 'ziethen',
  },
  {
    ids: [{ id: 537 }],
    name: 'Zinnowitz',
    region: 'W',
    slug: 'zinnowitz',
  },
  {
    ids: [{ id: 255 }],
    name: 'Zinzow',
    region: 'A',
    slug: 'zinzow',
  },
  {
    ids: [{ id: 538 }],
    name: 'Zirchow',
    region: 'W',
    slug: 'zirchow',
  },
  {
    ids: [{ id: 724 }],
    name: 'Züssow',
    region: 'G',
    slug: 'zuessow',
  },
];

const getVillage = slug => {
  return _.findWhere(villages, { slug: slug });
};

export default getVillage;
