import { findWhere } from 'underscore';

export const villages = [
  {
    ids: [{ id: 301 }],
    name: 'Ahlbeck',
    region: 'W',
    slug: 'ahlbeck',
  },
  {
    ids: [{ id: 1 }],
    name: 'Albinshof',
    region: 'A',
    slug: 'albinshof',
  },
  {
    ids: [{ id: 736 }],
    name: 'Alt Brüssow',
    region: 'G',
    slug: 'alt-bruessow',
  },
  {
    ids: [{ id: 2 }],
    name: 'Alt Kosenow',
    region: 'A',
    slug: 'alt-kosenow',
  },
  {
    ids: [{ id: 601 }],
    name: 'Alt Negentin',
    region: 'G',
    slug: 'alt-negentin',
  },
  {
    ids: [{ id: 602 }],
    name: 'Alt Pansow',
    region: 'G',
    slug: 'alt-pansow',
  },
  {
    ids: [{ id: 3 }],
    name: 'Alt Sanitz',
    region: 'A',
    slug: 'alt-sanitz',
  },
  {
    ids: [{ id: 4 }],
    name: 'Alt Teterin',
    region: 'A',
    slug: 'alt-teterin',
  },
  {
    ids: [{ id: 603 }],
    name: 'Alt Ungnade',
    region: 'G',
    slug: 'alt-ungnade',
  },
  {
    ids: [{ id: 5 }],
    name: 'Anklam',
    region: 'A',
    slug: 'anklam',
  },
  {
    ids: [{ id: 138 }],
    name: 'Anklamer Fähre',
    region: 'A',
    slug: 'anklamer-faehre',
  },
  {
    ids: [{ id: 13 }],
    name: 'Auerose',
    region: 'A',
    slug: 'auerose',
  },
  {
    ids: [{ id: 302 }],
    name: 'Balm',
    region: 'W',
    slug: 'balm',
  },
  {
    ids: [{ id: 604 }],
    name: 'Bandelin',
    region: 'G',
    slug: 'bandelin',
  },
  {
    ids: [{ id: 303 }],
    name: 'Bannemin',
    region: 'W',
    slug: 'bannemin',
  },
  {
    ids: [{ id: 304 }],
    name: 'Bansin',
    region: 'W',
    slug: 'bansin',
  },
  {
    ids: [{ id: 305 }],
    name: 'Bansin Dorf',
    region: 'W',
    slug: 'bansin-dorf',
  },
  {
    ids: [{ id: 140 }],
    name: 'Bargischow',
    region: 'A',
    slug: 'bargischow',
  },
  {
    ids: [{ id: 306 }],
    name: 'Bauer',
    region: 'W',
    slug: 'bauer',
  },
  {
    ids: [{ id: 605 }],
    name: 'Behrenhoff',
    region: 'G',
    slug: 'behrenhoff',
  },
  {
    ids: [{ id: 307 }],
    name: 'Benz',
    region: 'W',
    slug: 'benz',
  },
  {
    ids: [{ id: 141 }],
    name: 'Blesewitz',
    region: 'A',
    slug: 'blesewitz',
  },
  {
    ids: [{ id: 142 }],
    name: 'Boldekow',
    region: 'A',
    slug: 'boldekow',
  },
  {
    ids: [{ id: 606 }],
    name: 'Boltenhagen',
    region: 'G',
    slug: 'boltenhagen',
  },
  {
    ids: [{ id: 143 }],
    name: 'Bömitz',
    region: 'A',
    slug: 'boemitz',
  },
  {
    ids: [{ id: 144 }],
    name: 'Borntin',
    region: 'A',
    slug: 'borntin',
  },
  {
    ids: [{ id: 308 }],
    name: 'Bossin',
    region: 'W',
    slug: 'bossin',
  },
  {
    ids: [
      { id: 607, remark: 'außer Peenestr. 8-9a' },
      { id: 734, remark: 'nur Peenestr. 8-9a' },
    ],
    name: 'Breechen',
    region: 'G',
    slug: 'breechen',
  },
  {
    ids: [{ id: 145 }],
    name: 'Brenkenhof',
    region: 'A',
    slug: 'brenkenhof',
  },
  {
    ids: [{ id: 608 }],
    name: 'Brünzow',
    region: 'G',
    slug: 'bruenzow',
  },
  {
    ids: [{ id: 60 }],
    name: 'Brüssow',
    region: 'G',
    slug: 'bruessow',
  },
  {
    ids: [{ id: 30 }],
    name: 'Buddenhagen',
    region: 'W',
    slug: 'buddenhagen',
  },
  {
    ids: [{ id: 146 }],
    name: 'Bugewitz',
    region: 'A',
    slug: 'bugewitz',
  },
  {
    ids: [{ id: 310 }],
    name: 'Buggenhagen',
    region: 'W',
    slug: 'buggenhagen',
  },
  {
    ids: [{ id: 147 }],
    name: 'Buggow',
    region: 'A',
    slug: 'buggow',
  },
  {
    ids: [{ id: 610 }],
    name: 'Busdorf',
    region: 'G',
    slug: 'busdorf',
  },
  {
    ids: [{ id: 148 }],
    name: 'Busow',
    region: 'A',
    slug: 'busow',
  },
  {
    ids: [{ id: 14 }],
    name: 'Butzow',
    region: 'A',
    slug: 'butzow',
  },
  {
    ids: [{ id: 150 }],
    name: 'Charlottenhof',
    region: 'A',
    slug: 'charlottenhof',
  },
  {
    ids: [{ id: 611 }],
    name: 'Dambeck',
    region: 'G',
    slug: 'dambeck',
  },
  {
    ids: [{ id: 612 }],
    name: 'Dargelin',
    region: 'G',
    slug: 'dargelin',
    remark: '+ Dargelin Hof',
  },
  {
    ids: [{ id: 311 }],
    name: 'Dargen',
    region: 'W',
    slug: 'dargen',
  },
  {
    ids: [{ id: 613 }],
    name: 'Dargezin',
    region: 'G',
    slug: 'dargezin',
  },
  {
    ids: [{ id: 614 }],
    name: 'Dargezin Vorwerk',
    region: 'G',
    slug: 'dargezin-vorwerk',
  },
  {
    ids: [{ id: 151 }],
    name: 'Dargibell',
    region: 'A',
    slug: 'dargibell',
  },
  {
    ids: [{ id: 152 }],
    name: 'Daugzin',
    region: 'A',
    slug: 'daugzin',
  },
  {
    ids: [{ id: 153 }],
    name: 'Dennin',
    region: 'A',
    slug: 'dennin',
  },
  {
    ids: [{ id: 615 }],
    name: 'Dersekow',
    region: 'G',
    slug: 'dersekow',
  },
  {
    ids: [{ id: 154 }],
    name: 'Dersewitz',
    region: 'A',
    slug: 'dersewitz',
  },
  {
    ids: [{ id: 312 }],
    name: 'Dewichow',
    region: 'W',
    slug: 'dewichow',
  },
  {
    ids: [{ id: 616 }],
    name: 'Diedrichshagen',
    region: 'G',
    slug: 'diedrichshagen',
  },
  {
    ids: [{ id: 617 }],
    name: 'Dreizehnhausen',
    region: 'G',
    slug: 'dreizehnhausen',
  },
  {
    ids: [{ id: 155 }],
    name: 'Drewelow',
    region: 'A',
    slug: 'drewelow',
  },
  {
    ids: [{ id: 156 }],
    name: 'Ducherow',
    region: 'A',
    slug: 'ducherow',
  },
  {
    ids: [{ id: 157 }],
    name: 'Fasanenhof',
    region: 'A',
    slug: 'fasanenhof',
  },
  {
    ids: [{ id: 618 }],
    name: 'Frätow',
    region: 'G',
    slug: 'fraetow',
  },
  {
    ids: [{ id: 313 }],
    name: 'Freest',
    region: 'W',
    slug: 'freest',
  },
  {
    ids: [{ id: 61 }],
    name: 'Friedrichsfelde',
    region: 'G',
    slug: 'friedrichsfelde',
  },
  {
    ids: [{ id: 620 }],
    name: 'Fritzow',
    region: 'G',
    slug: 'fritzow',
  },
  {
    ids: [{ id: 621 }],
    name: 'Gahlkow',
    region: 'G',
    slug: 'gahlkow',
  },
  {
    ids: [{ id: 314 }],
    name: 'Garz',
    region: 'W',
    slug: 'garz',
  },
  {
    ids: [{ id: 158 }],
    name: 'Gellendin',
    region: 'A',
    slug: 'gellendin',
  },
  {
    ids: [{ id: 315 }],
    name: 'Gellenthin',
    region: 'W',
    slug: 'gellenthin',
  },
  {
    ids: [{ id: 622 }],
    name: 'Giesekenhagen',
    region: 'G',
    slug: 'giesekenhagen',
  },
  {
    ids: [{ id: 623 }],
    name: 'Gladrow',
    region: 'G',
    slug: 'gladrow',
  },
  {
    ids: [{ id: 15 }],
    name: 'Glien',
    region: 'A',
    slug: 'glien',
  },
  {
    ids: [{ id: 624 }],
    name: 'Glödenhof',
    region: 'G',
    slug: 'gloedenhof',
  },
  {
    ids: [{ id: 316 }],
    name: 'Gneventhin',
    region: 'W',
    slug: 'gneventhin',
  },
  {
    ids: [{ id: 160 }],
    name: 'Gnevezin',
    region: 'A',
    slug: 'gnevezin',
  },
  {
    ids: [{ id: 161 }],
    name: 'Görke, Postlow',
    region: 'A',
    slug: 'goerke-postlow',
  },
  {
    ids: [{ id: 317 }],
    name: 'Görke, Dargen',
    region: 'W',
    slug: 'goerke-dargen',
  },
  {
    ids: [{ id: 318 }],
    name: 'Gothen',
    region: 'W',
    slug: 'gothen',
  },
  {
    ids: [{ id: 162 }],
    name: 'Gramzow',
    region: 'A',
    slug: 'gramzow',
  },
  {
    ids: [{ id: 625 }],
    name: 'Gribow',
    region: 'G',
    slug: 'gribow',
  },
  {
    ids: [{ id: 626 }],
    name: 'Gristow',
    region: 'G',
    slug: 'gristow',
  },
  {
    ids: [{ id: 163 }],
    name: 'Groß Bünzow',
    region: 'A',
    slug: 'gross-buenzow',
  },
  {
    ids: [{ id: 31 }],
    name: 'Groß Ernsthof',
    region: 'W',
    slug: 'gross-ernsthof',
  },
  {
    ids: [{ id: 164 }],
    name: 'Groß Jasedow',
    region: 'A',
    slug: 'gross-jasedow',
  },
  {
    ids: [
      { id: 627, remark: 'außer Dorfstr. 6-6b und 7-11' },
      { id: 731, remark: 'nur Dorfstr. 6-6b und 7-11' },
    ],
    name: 'Groß Karrendorf',
    region: 'G',
    slug: 'gross-karrendorf',
  },
  {
    ids: [{ id: 628 }],
    name: 'Groß Kieshof',
    region: 'G',
    slug: 'gross-kieshof',
  },
  {
    ids: [{ id: 630 }],
    name: 'Groß Kiesow',
    region: 'G',
    slug: 'gross-kiesow',
    remark: '+ Groß Kiesow Meierei',
  },
  {
    ids: [{ id: 631 }],
    name: 'Groß Petershagen',
    region: 'G',
    slug: 'gross-petershagen',
  },
  {
    ids: [{ id: 165 }],
    name: 'Groß Polzin',
    region: 'A',
    slug: 'gross-polzin',
  },
  {
    ids: [{ id: 632 }],
    name: 'Grubenhagen',
    region: 'G',
    slug: 'grubenhagen',
  },
  {
    ids: [{ id: 320 }],
    name: 'Grüssow',
    region: 'W',
    slug: 'gruessow',
  },
  {
    ids: [{ id: 166 }],
    name: 'Grüttow',
    region: 'A',
    slug: 'gruettow',
  },
  {
    ids: [{ id: 633 }],
    name: 'Guest',
    region: 'G',
    slug: 'guest',
  },
  {
    ids: [{ id: 321 }],
    name: 'Gummlin',
    region: 'W',
    slug: 'gummlin',
  },
  {
    ids: [{ id: 634 }],
    name: 'Gustebin',
    region: 'G',
    slug: 'gustebin',
  },
  {
    ids: [
      { id: 635, remark: 'außer Gartenstr., Kleine Wallstr., Müllerwall, Töpferstr.' },
      { id: 735, remark: 'nur Gartenstr., Kleine Wallstr.,Müllerwall, Töpferstr.' },
    ],
    name: 'Gützkow',
    region: 'G',
    slug: 'guetzkow',
  },
  {
    ids: [{ id: 725 }],
    name: 'Gützkow-Meierei',
    region: 'G',
    slug: 'guetzkow-meierei',
  },
  {
    ids: [
      {
        id: 636,
        remark:
          'außer Am Gerstenberg, Hainweg, Obere Bachstraßen, Zum Grund, Zum Hellbusch, Zum Langenmoor',
      },
      {
        id: 727,
        remark:
          'nur Am Gerstenberg, Hainweg, Obere Bachstraßen, Zum Grund, Zum Hellbusch, Zum Langenmoor',
      },
    ],
    name: 'Hanshagen',
    region: 'G',
    slug: 'hanshagen',
  },
  {
    ids: [{ id: 167 }],
    name: 'Heidberg',
    region: 'A',
    slug: 'heidberg',
  },
  {
    ids: [{ id: 637 }],
    name: 'Heilgeisthof',
    region: 'G',
    slug: 'heilgeisthof',
  },
  {
    ids: [{ id: 638 }],
    name: 'Helmshagen',
    region: 'G',
    slug: 'helmshagen',
  },
  {
    ids: [{ id: 322 }],
    name: 'Heringsdorf',
    region: 'W',
    slug: 'heringsdorf',
  },
  {
    ids: [{ id: 324 }],
    name: 'Heringsdorf',
    region: 'W',
    slug: 'heringsdorf-neuhof',
  },
  {
    ids: [{ id: 63 }],
    name: 'Hinrichshagen',
    region: 'G',
    slug: 'hinrichshagen',
    remark: '+ Hof, Buchenberg, Siedlungen',
  },
  {
    ids: [{ id: 326 }],
    name: 'Hohendorf',
    region: 'W',
    slug: 'hohendorf',
  },
  {
    ids: [{ id: 327 }],
    name: 'Hohenfelde',
    region: 'W',
    slug: 'hohenfelde',
  },
  {
    ids: [{ id: 328 }],
    name: 'Hohensee',
    region: 'W',
    slug: 'hohensee',
  },
  {
    ids: [{ id: 32 }],
    name: 'Hollendorf',
    region: 'W',
    slug: 'hollendorf',
  },
  {
    ids: [{ id: 640 }],
    name: 'Immenhorst',
    region: 'G',
    slug: 'immenhorst',
  },
  {
    ids: [{ id: 168 }],
    name: 'Iven',
    region: 'A',
    slug: 'iven',
  },
  {
    ids: [{ id: 641 }],
    name: 'Jagdkrug',
    region: 'G',
    slug: 'jagdkrug',
  },
  {
    ids: [{ id: 642 }],
    name: 'Jägerhof',
    region: 'G',
    slug: 'jaegerhof',
  },
  {
    ids: [{ id: 330 }],
    name: 'Jamitzow',
    region: 'W',
    slug: 'jamitzow',
  },
  {
    ids: [{ id: 16 }],
    name: 'Janow',
    region: 'A',
    slug: 'janow',
  },
  {
    ids: [{ id: 170 }],
    name: 'Japenzin',
    region: 'A',
    slug: 'japenzin',
  },
  {
    ids: [{ id: 171 }],
    name: 'Jargelin',
    region: 'A',
    slug: 'jargelin',
  },
  {
    ids: [{ id: 643 }],
    name: 'Jarmshagen',
    region: 'G',
    slug: 'jarmshagen',
  },
  {
    ids: [{ id: 172 }],
    name: 'Johanneshof',
    region: 'A',
    slug: 'johanneshof',
  },
  {
    ids: [{ id: 644 }],
    name: 'Johannisthal',
    region: 'G',
    slug: 'johannisthal',
  },
  {
    ids: [{ id: 331 }],
    name: 'Kachlin',
    region: 'W',
    slug: 'kachlin',
  },
  {
    ids: [{ id: 173 }],
    name: 'Kagendorf',
    region: 'A',
    slug: 'kagendorf',
  },
  {
    ids: [{ id: 174 }],
    name: 'Kagenow',
    region: 'A',
    slug: 'kagenow',
  },
  {
    ids: [{ id: 175 }],
    name: 'Kalkstein',
    region: 'A',
    slug: 'kalkstein',
  },
  {
    ids: [{ id: 645 }],
    name: 'Kalkvitz',
    region: 'G',
    slug: 'kalkvitz',
  },
  {
    ids: [{ id: 646 }],
    name: 'Kammin',
    region: 'G',
    slug: 'kammin',
  },
  {
    ids: [{ id: 332 }],
    name: 'Kamminke',
    region: 'W',
    slug: 'kamminke',
  },
  {
    ids: [{ id: 176 }],
    name: 'Kamp',
    region: 'A',
    slug: 'kamp',
  },
  {
    ids: [{ id: 647 }],
    name: 'Karbow',
    region: 'G',
    slug: 'karbow',
  },
  {
    ids: [{ id: 648 }],
    name: 'Karlsburg',
    region: 'G',
    slug: 'karlsburg',
  },
  {
    ids: [{ id: 333 }],
    name: 'Karlshagen',
    region: 'W',
    slug: 'karlshagen',
  },
  {
    ids: [{ id: 334 }],
    name: 'Karnin',
    region: 'W',
    slug: 'karnin',
  },
  {
    ids: [{ id: 335 }],
    name: 'Karrin',
    region: 'W',
    slug: 'karrin',
  },
  {
    ids: [{ id: 336 }],
    name: 'Katschow',
    region: 'W',
    slug: 'katschow',
  },
  {
    ids: [{ id: 64 }],
    name: 'Katzow',
    region: 'G',
    slug: 'katzow',
  },
  {
    ids: [{ id: 177 }],
    name: 'Kavelpaß',
    region: 'A',
    slug: 'kavelpass',
  },
  {
    ids: [{ id: 650 }],
    name: 'Kemnitz',
    region: 'G',
    slug: 'kemnitz',
    remark: '+ Kemnitz-Meierei',
  },
  {
    ids: [
      { id: 651, remark: 'außer 11-19' },
      { id: 732, remark: 'nur 11-19' },
    ],
    name: 'Kemnitzerhagen',
    region: 'G',
    slug: 'kemnitzerhagen',
  },
  {
    ids: [{ id: 652 }],
    name: 'Kessin',
    region: 'G',
    slug: 'kessin',
  },
  {
    ids: [{ id: 62 }],
    name: 'Kieshof-Ausbau',
    region: 'G',
    slug: 'kieshof-ausbau',
  },
  {
    ids: [{ id: 178 }],
    name: 'Klein Below',
    region: 'A',
    slug: 'klein-below',
  },
  {
    ids: [{ id: 17 }],
    name: 'Klein Bünzow',
    region: 'A',
    slug: 'klein-buenzow',
  },
  {
    ids: [{ id: 260 }],
    name: 'Klein Bünzow Ausbau',
    region: 'A',
    slug: 'klein-buenzow-ausbau',
  },
  {
    ids: [{ id: 653 }],
    name: 'Klein Ernsthof',
    region: 'G',
    slug: 'klein-ernsthof',
  },
  {
    ids: [{ id: 337 }],
    name: 'Klein Jasedow',
    region: 'W',
    slug: 'klein-jasedow',
  },
  {
    ids: [{ id: 654 }],
    name: 'Klein Karrendorf',
    region: 'G',
    slug: 'klein-karrendorf',
  },
  {
    ids: [{ id: 655 }],
    name: 'Klein Kieshof',
    region: 'G',
    slug: 'klein-kieshof',
  },
  {
    ids: [{ id: 656 }],
    name: 'Klein Kiesow',
    region: 'G',
    slug: 'klein-kiesow',
  },
  {
    ids: [{ id: 657 }],
    name: 'Klein Petershagen',
    region: 'G',
    slug: 'klein-petershagen',
  },
  {
    ids: [{ id: 180 }],
    name: 'Klein Polzin',
    region: 'A',
    slug: 'klein-polzin',
  },
  {
    ids: [{ id: 658 }],
    name: 'Klein Schönwalde',
    region: 'G',
    slug: 'klein-schoenwalde',
  },
  {
    ids: [{ id: 65 }],
    name: 'Klein Zastrow',
    region: 'G',
    slug: 'klein-zastrow',
  },
  {
    ids: [{ id: 181 }],
    name: 'Klitschendorf',
    region: 'A',
    slug: 'klitschendorf',
  },
  {
    ids: [
      { id: 338, remark: 'außer Lindenallee' },
      { id: 543, remark: 'nur Lindenallee' },
    ],
    name: 'Klotzow',
    region: 'W',
    slug: 'klotzow',
  },
  {
    ids: [{ id: 33 }],
    name: 'Kölpin',
    region: 'W',
    slug: 'koelpin',
  },
  {
    ids: [{ id: 340 }],
    name: 'Kölpinsee',
    region: 'W',
    slug: 'koelpinsee',
  },
  {
    ids: [{ id: 660 }],
    name: 'Kölzin',
    region: 'G',
    slug: 'koelzin',
  },
  {
    ids: [{ id: 661 }],
    name: 'Konerow',
    region: 'G',
    slug: 'konerow',
  },
  {
    ids: [{ id: 182 }],
    name: 'Konsages',
    region: 'A',
    slug: 'konsages',
  },
  {
    ids: [{ id: 341 }],
    name: 'Korswandt',
    region: 'W',
    slug: 'korswandt',
  },
  {
    ids: [{ id: 342 }],
    name: 'Koserow',
    region: 'W',
    slug: 'koserow',
  },
  {
    ids: [{ id: 662 }],
    name: 'Kowall',
    region: 'G',
    slug: 'kowall',
  },
  {
    ids: [{ id: 663 }],
    name: 'Kräpelin',
    region: 'G',
    slug: 'kraepelin',
  },
  {
    ids: [{ id: 664 }],
    name: 'Krebsow',
    region: 'G',
    slug: 'krebsow',
  },
  {
    ids: [{ id: 183 }],
    name: 'Krenzow',
    region: 'A',
    slug: 'krenzow',
  },
  {
    ids: [{ id: 184 }],
    name: 'Krien',
    region: 'A',
    slug: 'krien',
  },
  {
    ids: [{ id: 185 }],
    name: 'Krien-Horst',
    region: 'A',
    slug: 'krien-horst',
  },
  {
    ids: [{ id: 343 }],
    name: 'Krienke',
    region: 'W',
    slug: 'krienke',
  },
  {
    ids: [{ id: 344 }],
    name: 'Kröslin',
    region: 'W',
    slug: 'kroeslin',
  },
  {
    ids: [{ id: 345 }],
    name: 'Krummin',
    region: 'W',
    slug: 'krummin',
  },
  {
    ids: [{ id: 186 }],
    name: 'Krusenfelde',
    region: 'A',
    slug: 'krusenfelde',
  },
  {
    ids: [{ id: 187 }],
    name: 'Krusenkrien',
    region: 'A',
    slug: 'krusenkrien',
  },
  {
    ids: [{ id: 665 }],
    name: 'Kühlenhagen',
    region: 'G',
    slug: 'kuehlenhagen',
  },
  {
    ids: [{ id: 666 }],
    name: 'Kuntzow',
    region: 'G',
    slug: 'kuntzow',
  },
  {
    ids: [{ id: 188 }],
    name: 'Kurtshagen',
    region: 'A',
    slug: 'kurtshagen',
  },
  {
    ids: [{ id: 346 }],
    name: 'Kutzow',
    region: 'W',
    slug: 'kutzow',
  },
  {
    ids: [{ id: 347 }],
    name: 'Labömitz',
    region: 'W',
    slug: 'laboemitz',
  },
  {
    ids: [{ id: 348 }],
    name: 'Lassan',
    region: 'W',
    slug: 'lassan',
  },
  {
    ids: [{ id: 667 }],
    name: 'Latzow',
    region: 'G',
    slug: 'latzow',
  },
  {
    ids: [{ id: 668 }],
    name: 'Leist',
    region: 'G',
    slug: 'leist',
  },
  {
    ids: [{ id: 18 }],
    name: 'Lentschow',
    region: 'A',
    slug: 'lentschow',
  },
  {
    ids: [{ id: 66 }],
    name: 'Levenhagen',
    region: 'G',
    slug: 'levenhagen',
  },
  {
    ids: [{ id: 190 }],
    name: 'Libnow',
    region: 'A',
    slug: 'libnow',
  },
  {
    ids: [{ id: 34 }],
    name: 'Liepe',
    region: 'W',
    slug: 'liepe',
  },
  {
    ids: [{ id: 191 }],
    name: 'Liepen',
    region: 'A',
    slug: 'liepen',
  },
  {
    ids: [{ id: 350 }],
    name: 'Loddin',
    region: 'W',
    slug: 'loddin',
  },
  {
    ids: [{ id: 670 }],
    name: 'Lodmannshagen',
    region: 'G',
    slug: 'lodmannshagen',
  },
  {
    ids: [{ id: 671 }],
    name: 'Loissin',
    region: 'G',
    slug: 'loissin',
  },
  {
    ids: [{ id: 192 }],
    name: 'Löwitz',
    region: 'A',
    slug: 'loewitz',
  },
  {
    ids: [{ id: 672 }],
    name: 'Lubmin',
    region: 'G',
    slug: 'lubmin',
  },
  {
    ids: [{ id: 193 }],
    name: 'Lucienhof',
    region: 'A',
    slug: 'lucienhof',
  },
  {
    ids: [{ id: 673 }],
    name: 'Ludwigsburg',
    region: 'G',
    slug: 'ludwigsburg',
  },
  {
    ids: [{ id: 674 }],
    name: 'Lühmannsdorf',
    region: 'G',
    slug: 'luehmannsdorf',
  },
  {
    ids: [{ id: 194 }],
    name: 'Lüskow',
    region: 'A',
    slug: 'lueskow',
  },
  {
    ids: [{ id: 675 }],
    name: 'Lüssow',
    region: 'G',
    slug: 'luessow',
  },
  {
    ids: [{ id: 351 }],
    name: 'Lütow',
    region: 'W',
    slug: 'luetow',
  },
  {
    ids: [{ id: 352 }],
    name: 'Mahlzow',
    region: 'W',
    slug: 'mahlzow',
  },
  {
    ids: [{ id: 195 }],
    name: 'Marienthal',
    region: 'A',
    slug: 'marienthal',
  },
  {
    ids: [{ id: 196 }],
    name: 'Medow',
    region: 'A',
    slug: 'medow',
  },
  {
    ids: [{ id: 353 }],
    name: 'Mellenthin',
    region: 'W',
    slug: 'mellenthin',
  },
  {
    ids: [{ id: 197 }],
    name: 'Menzlin',
    region: 'A',
    slug: 'menzlin',
  },
  {
    ids: [{ id: 676 }],
    name: 'Mesekenhagen',
    region: 'G',
    slug: 'mesekenhagen',
  },
  {
    ids: [{ id: 354 }],
    name: 'Milchhorst',
    region: 'W',
    slug: 'milchhorst',
  },
  {
    ids: [{ id: 677 }],
    name: 'Moeckow',
    region: 'G',
    slug: 'moeckow',
    remark: '+ Moeckow-Berg',
  },
  {
    ids: [{ id: 355 }],
    name: 'Mölschow',
    region: 'W',
    slug: 'moelschow',
  },
  {
    ids: [{ id: 356 }],
    name: 'Mönchow',
    region: 'W',
    slug: 'moenchow',
  },
  {
    ids: [{ id: 357 }],
    name: 'Morgenitz',
    region: 'W',
    slug: 'morgenitz',
  },
  {
    ids: [{ id: 198 }],
    name: 'Müggenburg',
    region: 'A',
    slug: 'mueggenburg',
  },
  {
    ids: [{ id: 19 }],
    name: 'Murchin',
    region: 'A',
    slug: 'murchin',
  },
  {
    ids: [{ id: 678 }],
    name: 'Müssow',
    region: 'G',
    slug: 'muessow',
  },
  {
    ids: [{ id: 358 }],
    name: 'Neeberg',
    region: 'W',
    slug: 'neeberg',
  },
  {
    ids: [{ id: 200 }],
    name: 'Neetzow',
    region: 'A',
    slug: 'neetzow',
  },
  {
    ids: [{ id: 35 }],
    name: 'Negenmark',
    region: 'W',
    slug: 'negenmark',
  },
  {
    ids: [{ id: 360 }],
    name: 'Neppermin',
    region: 'W',
    slug: 'neppermin',
  },
  {
    ids: [{ id: 67 }],
    name: 'Nepzin',
    region: 'G',
    slug: 'nepzin',
  },
  {
    ids: [{ id: 201 }],
    name: 'Nerdin',
    region: 'A',
    slug: 'nerdin',
  },
  {
    ids: [{ id: 680 }],
    name: 'Netzeband',
    region: 'G',
    slug: 'netzeband',
  },
  {
    ids: [{ id: 361 }],
    name: 'Netzelkow',
    region: 'W',
    slug: 'netzelkow',
  },
  {
    ids: [{ id: 681 }],
    name: 'Neu Boltenhagen',
    region: 'G',
    slug: 'neu-boltenhagen',
  },
  {
    ids: [{ id: 682 }],
    name: 'Neu Dargelin',
    region: 'G',
    slug: 'neu-dargelin',
  },
  {
    ids: [{ id: 202 }],
    name: 'Neu Kosenow',
    region: 'A',
    slug: 'neu-kosenow',
  },
  {
    ids: [{ id: 203 }],
    name: 'Neu Krien',
    region: 'A',
    slug: 'neu-krien',
  },
  {
    ids: [{ id: 683 }],
    name: 'Neu Negentin',
    region: 'G',
    slug: 'neu-negentin',
  },
  {
    ids: [{ id: 684 }],
    name: 'Neu Pansow',
    region: 'G',
    slug: 'neu-pansow',
  },
  {
    ids: [{ id: 362 }],
    name: 'Neu Pudagla',
    region: 'W',
    slug: 'neu-pudagla',
  },
  {
    ids: [{ id: 363 }],
    name: 'Neu Sallenthin',
    region: 'W',
    slug: 'neu-sallenthin',
  },
  {
    ids: [{ id: 204 }],
    name: 'Neu Sanitz',
    region: 'A',
    slug: 'neu-sanitz',
  },
  {
    ids: [{ id: 205 }],
    name: 'Neu Teterin',
    region: 'A',
    slug: 'neu-teterin',
  },
  {
    ids: [{ id: 685 }],
    name: 'Neu Ungnade',
    region: 'G',
    slug: 'neu-ungnade',
  },
  {
    ids: [{ id: 364 }],
    name: 'Neuendorf, Lütow',
    region: 'W',
    slug: 'neuendorf-luetow',
  },
  {
    ids: [{ id: 686 }],
    name: 'Neuendorf, Gützkow',
    region: 'G',
    slug: 'neuendorf-guetzkow',
  },
  {
    ids: [{ id: 687 }],
    name: 'Neuendorf, Kemnitz',
    region: 'G',
    slug: 'neuendorf-kemnitz',
    remark: '+ Neuendorf-Ausbau',
  },
  {
    ids: [{ id: 206 }],
    name: 'Neuendorf A, Ducherow',
    region: 'A',
    slug: 'neuendorf-a-ducherow',
  },
  {
    ids: [{ id: 207 }],
    name: 'Neuendorf B, Spantekow',
    region: 'A',
    slug: 'neuendorf-b-spantekow',
  },
  {
    ids: [{ id: 208 }],
    name: 'Neuenkirchen (bei Anklam)',
    region: 'A',
    slug: 'neuenkirchen-bei-anklam',
  },
  {
    ids: [{ id: 688 }],
    name: 'Neuenkirchen (bei Greifswald)',
    region: 'G',
    slug: 'neuenkirchen-bei-greifswald',
  },
  {
    ids: [{ id: 20 }],
    name: 'Neuhof, Stolpe an der Peene',
    region: 'A',
    slug: 'neuhof-stolpe-an-der-peene',
  },
  {
    ids: [{ id: 365 }],
    name: 'Neverow',
    region: 'W',
    slug: 'neverow',
  },
  {
    ids: [{ id: 68 }],
    name: 'Nonnendorf',
    region: 'G',
    slug: 'nonnendorf',
  },
  {
    ids: [{ id: 690 }],
    name: 'Oldenburg',
    region: 'G',
    slug: 'oldenburg',
  },
  {
    ids: [{ id: 691 }],
    name: 'Oldenhagen',
    region: 'G',
    slug: 'oldenhagen',
  },
  {
    ids: [{ id: 366 }],
    name: 'Ostklüne',
    region: 'W',
    slug: 'ostkluene',
  },
  {
    ids: [{ id: 692 }],
    name: 'Owstin',
    region: 'G',
    slug: 'owstin',
  },
  {
    ids: [{ id: 210 }],
    name: 'Padderow',
    region: 'A',
    slug: 'padderow',
  },
  {
    ids: [{ id: 211 }],
    name: 'Pamitz',
    region: 'A',
    slug: 'pamitz',
  },
  {
    ids: [{ id: 212 }],
    name: 'Panschow',
    region: 'A',
    slug: 'panschow',
  },
  {
    ids: [{ id: 367 }],
    name: 'Papendorf',
    region: 'W',
    slug: 'papendorf',
  },
  {
    ids: [{ id: 368 }],
    name: 'Paske',
    region: 'W',
    slug: 'paske',
  },
  {
    ids: [{ id: 213 }],
    name: 'Pätschow',
    region: 'A',
    slug: 'paetschow',
  },
  {
    ids: [{ id: 36 }],
    name: 'Peenemünde',
    region: 'W',
    slug: 'peenemuende',
  },
  {
    ids: [{ id: 214 }],
    name: 'Pelsin',
    region: 'A',
    slug: 'pelsin',
  },
  {
    ids: [{ id: 693 }],
    name: 'Pentin',
    region: 'G',
    slug: 'pentin',
  },
  {
    ids: [{ id: 215 }],
    name: 'Pinnow',
    region: 'A',
    slug: 'pinnow',
  },
  {
    ids: [{ id: 216 }],
    name: 'Postlow',
    region: 'A',
    slug: 'postlow',
  },
  {
    ids: [{ id: 694 }],
    name: 'Potthagen',
    region: 'G',
    slug: 'potthagen',
  },
  {
    ids: [{ id: 370 }],
    name: 'Prätenow',
    region: 'W',
    slug: 'praetenow',
  },
  {
    ids: [{ id: 217 }],
    name: 'Preetzen',
    region: 'A',
    slug: 'preetzen',
  },
  {
    ids: [{ id: 218 }],
    name: 'Priemen',
    region: 'A',
    slug: 'priemen',
  },
  {
    ids: [{ id: 371 }],
    name: 'Pritzier',
    region: 'W',
    slug: 'pritzier',
  },
  {
    ids: [{ id: 695 }],
    name: 'Pritzwald',
    region: 'G',
    slug: 'pritzwald',
  },
  {
    ids: [{ id: 372 }],
    name: 'Pudagla',
    region: 'W',
    slug: 'pudagla',
  },
  {
    ids: [{ id: 373 }],
    name: 'Pulow',
    region: 'W',
    slug: 'pulow',
  },
  {
    ids: [{ id: 21 }],
    name: 'Putzar',
    region: 'A',
    slug: 'putzar',
  },
  {
    ids: [{ id: 374 }],
    name: 'Quilitz',
    region: 'W',
    slug: 'quilitz',
  },
  {
    ids: [{ id: 220 }],
    name: 'Quilow',
    region: 'A',
    slug: 'quilow',
  },
  {
    ids: [
      { id: 696, remark: 'außer Am Felde 26-27' },
      { id: 733, remark: 'nur Am Felde 26-27' },
    ],
    name: 'Radlow',
    region: 'G',
    slug: 'radlow',
  },
  {
    ids: [{ id: 221 }],
    name: 'Ramitzow',
    region: 'A',
    slug: 'ramitzow',
  },
  {
    ids: [{ id: 375 }],
    name: 'Rankwitz',
    region: 'W',
    slug: 'rankwitz',
  },
  {
    ids: [{ id: 697 }],
    name: 'Ranzin',
    region: 'G',
    slug: 'ranzin',
  },
  {
    ids: [{ id: 698 }],
    name: 'Rappenhagen',
    region: 'G',
    slug: 'rappenhagen',
  },
  {
    ids: [{ id: 222 }],
    name: 'Rathebur',
    region: 'A',
    slug: 'rathebur',
  },
  {
    ids: [{ id: 223 }],
    name: 'Rebelow',
    region: 'A',
    slug: 'rebelow',
  },
  {
    ids: [{ id: 376 }],
    name: 'Reestow',
    region: 'W',
    slug: 'reestow',
  },
  {
    ids: [{ id: 377 }],
    name: 'Reetzow',
    region: 'W',
    slug: 'reetzow',
  },
  {
    ids: [{ id: 224 }],
    name: 'Rehberg',
    region: 'A',
    slug: 'rehberg',
  },
  {
    ids: [{ id: 225 }],
    name: 'Relzow',
    region: 'A',
    slug: 'relzow',
  },
  {
    ids: [{ id: 226 }],
    name: 'Rosenhagen',
    region: 'A',
    slug: 'rosenhagen',
  },
  {
    ids: [{ id: 227 }],
    name: 'Rossin',
    region: 'A',
    slug: 'rossin',
  },
  {
    ids: [{ id: 228 }],
    name: 'Rubenow, Boldekow',
    region: 'A',
    slug: 'rubenow-boldekow',
  },
  {
    ids: [{ id: 69 }],
    name: 'Rubenow',
    region: 'G',
    slug: 'rubenow',
  },
  {
    ids: [{ id: 22 }],
    name: 'Rubkow',
    region: 'A',
    slug: 'rubkow',
  },
  {
    ids: [{ id: 230 }],
    name: 'Salchow',
    region: 'A',
    slug: 'salchow',
  },
  {
    ids: [{ id: 378 }],
    name: 'Sallenthin',
    region: 'W',
    slug: 'sallenthin',
  },
  {
    ids: [{ id: 700 }],
    name: 'Sanz',
    region: 'G',
    slug: 'sanz',
  },
  {
    ids: [{ id: 231 }],
    name: 'Sarnow',
    region: 'A',
    slug: 'sarnow',
  },
  {
    ids: [{ id: 37 }],
    name: 'Sauzin',
    region: 'W',
    slug: 'sauzin',
  },
  {
    ids: [{ id: 380 }],
    name: 'Schalense',
    region: 'W',
    slug: 'schalense',
  },
  {
    ids: [{ id: 701 }],
    name: 'Schlagtow',
    region: 'G',
    slug: 'schlagtow',
  },
  {
    ids: [{ id: 702 }],
    name: 'Schlagtow-Meierei',
    region: 'G',
    slug: 'schlagtow-meierei',
  },
  {
    ids: [{ id: 232 }],
    name: 'Schlatkow',
    region: 'A',
    slug: 'schlatkow',
  },
  {
    ids: [{ id: 233 }],
    name: 'Schmatzin',
    region: 'A',
    slug: 'schmatzin',
  },
  {
    ids: [{ id: 703 }],
    name: 'Schmoldow',
    region: 'G',
    slug: 'schmoldow',
  },
  {
    ids: [{ id: 234 }],
    name: 'Schmuggerow',
    region: 'A',
    slug: 'schmuggerow',
  },
  {
    ids: [{ id: 235 }],
    name: 'Schwerinsburg',
    region: 'A',
    slug: 'schwerinsburg',
  },
  {
    ids: [{ id: 236 }],
    name: 'Schwerinshorst',
    region: 'A',
    slug: 'schwerinshorst',
  },
  {
    ids: [{ id: 381 }],
    name: 'Seckeritz',
    region: 'W',
    slug: 'seckeritz',
  },
  {
    ids: [{ id: 382 }],
    name: 'Sellin',
    region: 'W',
    slug: 'sellin',
  },
  {
    ids: [{ id: 704 }],
    name: 'Sestelin',
    region: 'G',
    slug: 'sestelin',
  },
  {
    ids: [{ id: 237 }],
    name: 'Sophienhof',
    region: 'A',
    slug: 'sophienhof',
  },
  {
    ids: [{ id: 383 }],
    name: 'Spandowerhagen',
    region: 'W',
    slug: 'spandowerhagen',
  },
  {
    ids: [{ id: 238 }],
    name: 'Spantekow',
    region: 'A',
    slug: 'spantekow',
  },
  {
    ids: [{ id: 384 }],
    name: 'Stagnieß',
    region: 'W',
    slug: 'stagniess',
  },
  {
    ids: [{ id: 23 }],
    name: 'Stammersfelde',
    region: 'A',
    slug: 'stammersfelde',
  },
  {
    ids: [{ id: 705 }],
    name: 'Steffenshagen',
    region: 'G',
    slug: 'steffenshagen',
  },
  {
    ids: [{ id: 706 }],
    name: 'Steinfurth',
    region: 'G',
    slug: 'steinfurth',
  },
  {
    ids: [{ id: 240 }],
    name: 'Steinmocker',
    region: 'A',
    slug: 'steinmocker',
  },
  {
    ids: [{ id: 707 }],
    name: 'Stevelin',
    region: 'G',
    slug: 'stevelin',
  },
  {
    ids: [{ id: 708 }],
    name: 'Stilow',
    region: 'G',
    slug: 'stilow',
  },
  {
    ids: [{ id: 70 }],
    name: 'Stilow-Siedlung',
    region: 'G',
    slug: 'stilow-siedlung',
  },
  {
    ids: [{ id: 385 }],
    name: 'Stoben',
    region: 'W',
    slug: 'stoben',
  },
  {
    ids: [{ id: 241 }],
    name: 'Stolpe an der Peene',
    region: 'A',
    slug: 'stolpe-an-der-peene',
  },
  {
    ids: [{ id: 386 }],
    name: 'Stolpe auf Usedom',
    region: 'W',
    slug: 'stolpe-auf-usedom',
  },
  {
    ids: [{ id: 710 }],
    name: 'Strellin',
    region: 'G',
    slug: 'strellin',
  },
  {
    ids: [{ id: 711 }],
    name: 'Stresow',
    region: 'G',
    slug: 'stresow',
    remark: '+ Stresow-Siedlung',
  },
  {
    ids: [{ id: 242 }],
    name: 'Stretense',
    region: 'A',
    slug: 'stretense',
  },
  {
    ids: [{ id: 243 }],
    name: 'Strippow',
    region: 'A',
    slug: 'strippow',
  },
  {
    ids: [{ id: 387 }],
    name: 'Stubbenfelde',
    region: 'W',
    slug: 'stubbenfelde',
  },
  {
    ids: [{ id: 712 }],
    name: 'Subzow',
    region: 'G',
    slug: 'subzow',
  },
  {
    ids: [{ id: 388 }],
    name: 'Suckow',
    region: 'W',
    slug: 'suckow',
  },
  {
    ids: [{ id: 244 }],
    name: 'Thurow',
    region: 'A',
    slug: 'thurow',
  },
  {
    ids: [{ id: 713 }],
    name: 'Thurow',
    region: 'G',
    slug: 'thurow',
  },
  {
    ids: [{ id: 245 }],
    name: 'Tramstow',
    region: 'A',
    slug: 'tramstow',
  },
  {
    ids: [{ id: 38 }],
    name: 'Trassenheide',
    region: 'W',
    slug: 'trassenheide',
  },
  {
    ids: [{ id: 390 }],
    name: 'Ückeritz',
    region: 'W',
    slug: 'ueckeritz',
  },
  {
    ids: [{ id: 391 }],
    name: 'Ulrichshorst',
    region: 'W',
    slug: 'ulrichshorst',
  },
  {
    ids: [{ id: 714 }],
    name: 'Upatel',
    region: 'G',
    slug: 'upatel',
  },
  {
    ids: [{ id: 392 }],
    name: 'Usedom',
    region: 'W',
    slug: 'usedom',
  },
  {
    ids: [{ id: 715 }],
    name: 'Vargatz',
    region: 'G',
    slug: 'vargatz',
  },
  {
    ids: [{ id: 716 }],
    name: 'Vierow',
    region: 'G',
    slug: 'vierow',
  },
  {
    ids: [{ id: 246 }],
    name: 'Vitense',
    region: 'A',
    slug: 'vitense',
  },
  {
    ids: [{ id: 717 }],
    name: 'Voddow',
    region: 'G',
    slug: 'voddow',
    remark: '+ Nieder-Voddow',
  },
  {
    ids: [{ id: 393 }],
    name: 'Voßberg',
    region: 'W',
    slug: 'vossberg',
  },
  {
    ids: [{ id: 718 }],
    name: 'Wackerow',
    region: 'G',
    slug: 'wackerow',
  },
  {
    ids: [{ id: 247 }],
    name: 'Wahlendow',
    region: 'A',
    slug: 'wahlendow',
  },
  {
    ids: [{ id: 71 }],
    name: 'Wampen',
    region: 'G',
    slug: 'wampen',
  },
  {
    ids: [{ id: 394 }],
    name: 'Wangelkow',
    region: 'W',
    slug: 'wangelkow',
  },
  {
    ids: [{ id: 395 }],
    name: 'Warthe',
    region: 'W',
    slug: 'warthe',
  },
  {
    ids: [{ id: 396 }],
    name: 'Waschow',
    region: 'W',
    slug: 'waschow',
  },
  {
    ids: [{ id: 248 }],
    name: 'Wegezin',
    region: 'A',
    slug: 'wegezin',
  },
  {
    ids: [{ id: 397 }],
    name: 'Wehrland',
    region: 'W',
    slug: 'wehrland',
  },
  {
    ids: [{ id: 398 }],
    name: 'Weiblitz',
    region: 'W',
    slug: 'weiblitz',
  },
  {
    ids: [{ id: 720 }],
    name: 'Weitenhagen',
    region: 'G',
    slug: 'weitenhagen',
  },
  {
    ids: [{ id: 39 }],
    name: 'Welzin',
    region: 'W',
    slug: 'welzin',
  },
  {
    ids: [{ id: 400 }],
    name: 'West-Klüne',
    region: 'W',
    slug: 'west-kluene',
  },
  {
    ids: [{ id: 401 }],
    name: 'Wilhelmsfelde',
    region: 'W',
    slug: 'wilhelmsfelde',
  },
  {
    ids: [{ id: 402 }],
    name: 'Wilhelmshof',
    region: 'W',
    slug: 'wilhelmshof',
  },
  {
    ids: [{ id: 24 }],
    name: 'Wolfradshof',
    region: 'A',
    slug: 'wolfradshof',
  },
  {
    ids: [{ id: 403 }],
    name: 'Wolgast',
    region: 'W',
    slug: 'wolgast',
  },
  {
    ids: [{ id: 250 }],
    name: 'Woserow',
    region: 'A',
    slug: 'woserow',
  },
  {
    ids: [{ id: 721 }],
    name: 'Wrangelsburg',
    region: 'G',
    slug: 'wrangelsburg',
  },
  {
    ids: [{ id: 251 }],
    name: 'Wusseken',
    region: 'A',
    slug: 'wusseken',
  },
  {
    ids: [{ id: 252 }],
    name: 'Wussentin',
    region: 'A',
    slug: 'wussentin',
  },
  {
    ids: [{ id: 256 }],
    name: 'Wussentin-Ausbau',
    region: 'A',
    slug: 'wussentin-ausbau',
  },
  {
    ids: [{ id: 722 }],
    name: 'Wusterhusen',
    region: 'G',
    slug: 'wusterhusen',
  },
  {
    ids: [{ id: 726 }],
    name: 'Wusterhusen',
    region: 'G',
    slug: 'wusterhusen-neubauten',
  },
  {
    ids: [{ id: 723 }],
    name: 'Zarnekow',
    region: 'G',
    slug: 'zarnekow',
  },
  {
    ids: [{ id: 531 }],
    name: 'Zarnitz',
    region: 'W',
    slug: 'zarnitz',
  },
  {
    ids: [{ id: 253 }],
    name: 'Zarrentin',
    region: 'A',
    slug: 'zarrentin',
  },
  {
    ids: [{ id: 532 }],
    name: 'Zecherin, Usedom',
    region: 'W',
    slug: 'zecherin-usedom',
  },
  {
    ids: [{ id: 533 }],
    name: 'Zecherin, Mölschow',
    region: 'W',
    slug: 'zecherin-moelschow',
  },
  {
    ids: [{ id: 534 }],
    name: 'Zemitz',
    region: 'W',
    slug: 'zemitz',
  },
  {
    ids: [{ id: 535 }],
    name: 'Zempin',
    region: 'W',
    slug: 'zempin',
  },
  {
    ids: [{ id: 536 }],
    name: 'Ziemitz',
    region: 'W',
    slug: 'ziemitz',
  },
  {
    ids: [{ id: 254 }],
    name: 'Ziethen',
    region: 'A',
    slug: 'ziethen',
  },
  {
    ids: [{ id: 537 }],
    name: 'Zinnowitz',
    region: 'W',
    slug: 'zinnowitz',
  },
  {
    ids: [{ id: 255 }],
    name: 'Zinzow',
    region: 'A',
    slug: 'zinzow',
  },
  {
    ids: [{ id: 538 }],
    name: 'Zirchow',
    region: 'W',
    slug: 'zirchow',
  },
  {
    ids: [{ id: 724 }],
    name: 'Züssow',
    region: 'G',
    slug: 'zuessow',
  },

  {
    ids: [{ id: 1001 }],
    name: 'Ahlbeck',
    region: 'U',
    slug: 'ahlbeck',
  },
  {
    ids: [{ id: 1002 }],
    name: 'Altwarp',
    region: 'U',
    slug: 'altwarp',
  },
  {
    ids: [{ id: 1003 }],
    name: 'Altwigshagen',
    region: 'U',
    slug: 'altwigshagen',
  },
  {
    ids: [{ id: 1004 }],
    name: 'Annenhof',
    region: 'U',
    slug: 'annenhof',
  },
  {
    ids: [{ id: 1005 }],
    name: 'Aschersleben',
    region: 'U',
    slug: 'aschersleben',
  },
  {
    ids: [{ id: 1322 }],
    name: 'Battinsthal',
    region: 'U',
    slug: 'battinsthal',
  },
  {
    ids: [{ id: 1006 }],
    name: 'Bellin',
    region: 'U',
    slug: 'bellin',
  },
  {
    ids: [{ id: 1323 }],
    name: 'Belling',
    region: 'U',
    slug: 'belling',
  },
  {
    ids: [{ id: 1324 }],
    name: 'Bergholz',
    region: 'U',
    slug: 'bergholz',
  },
  {
    ids: [{ id: 1007 }],
    name: 'Berndshof',
    region: 'U',
    slug: 'berndshof',
  },
  {
    ids: [{ id: 1325 }],
    name: 'Bismark',
    region: 'U',
    slug: 'bismark',
  },
  {
    ids: [{ id: 1326 }],
    name: 'Blankensee',
    region: 'U',
    slug: 'blankensee',
  },
  {
    ids: [{ id: 1327 }],
    name: 'Blockshof',
    region: 'U',
    slug: 'blockshof',
  },
  {
    ids: [{ id: 1328 }],
    name: 'Blumenhagen',
    region: 'U',
    slug: 'blumenhagen',
  },
  {
    ids: [{ id: 1008 }],
    name: 'Blumenthal',
    region: 'U',
    slug: 'blumenthal',
  },
  {
    ids: [{ id: 1329 }],
    name: 'Boldshof',
    region: 'U',
    slug: 'boldshof',
  },
  {
    ids: [{ id: 1330 }],
    name: 'Boock',
    region: 'U',
    slug: 'boock',
  },
  {
    ids: [{ id: 1009 }],
    name: 'Borckenfriede',
    region: 'U',
    slug: 'borckenfriede',
  },
  {
    ids: [{ id: 1335 }],
    name: 'Borgwall',
    region: 'U',
    slug: 'borgwall',
  },
  {
    ids: [{ id: 1331 }],
    name: 'Borken',
    region: 'U',
    slug: 'borken',
  },
  {
    ids: [{ id: 1332 }],
    name: 'Breitenstein',
    region: 'U',
    slug: 'breitenstein',
  },
  {
    ids: [{ id: 1333 }],
    name: 'Brietzig',
    region: 'U',
    slug: 'brietzig',
  },
  {
    ids: [{ id: 1334 }],
    name: 'Broellin',
    region: 'U',
    slug: 'broellin',
  },
  {
    ids: [{ id: 1336 }],
    name: 'Büssow',
    region: 'U',
    slug: 'buessow',
  },
  {
    ids: [{ id: 1337 }],
    name: 'Caselow',
    region: 'U',
    slug: 'caselow',
  },
  {
    ids: [{ id: 1338 }],
    name: 'Damerow',
    region: 'U',
    slug: 'damerow',
  },
  {
    ids: [{ id: 1339 }],
    name: 'Dargitz',
    region: 'U',
    slug: 'dargitz',
  },
  {
    ids: [{ id: 1010 }],
    name: 'Demnitz',
    region: 'U',
    slug: 'demnitz',
  },
  {
    ids: [{ id: 1340 }],
    name: 'Dorotheenwalde',
    region: 'U',
    slug: 'dorotheenwalde',
  },
  {
    ids: [{ id: 1011 }],
    name: 'Eggesin',
    region: 'U',
    slug: 'eggesin',
  },
  {
    ids: [{ id: 1054 }],
    name: 'Eichhof',
    region: 'U',
    slug: 'eichhof',
  },
  {
    ids: [{ id: 1341 }],
    name: 'Fahrenwalde',
    region: 'U',
    slug: 'fahrenwalde',
  },
  {
    ids: [{ id: 1055 }],
    name: 'Ferdinandshof',
    region: 'U',
    slug: 'ferdinandshof',
  },
  {
    ids: [{ id: 1076 }],
    name: 'Finkenbrück',
    region: 'U',
    slug: 'finkenbrueck',
  },
  {
    ids: [{ id: 1077 }],
    name: 'Fleethof',
    region: 'U',
    slug: 'fleethof',
  },
  {
    ids: [{ id: 1342 }],
    name: 'Franzfelde',
    region: 'U',
    slug: 'franzfelde',
  },
  {
    ids: [{ id: 1343 }],
    name: 'Freienstein',
    region: 'U',
    slug: 'freienstein',
  },
  {
    ids: [{ id: 1344 }],
    name: 'Friedberg',
    region: 'U',
    slug: 'friedberg',
  },
  {
    ids: [{ id: 1345 }],
    name: 'Friedefeld',
    region: 'U',
    slug: 'friedefeld',
  },
  {
    ids: [{ id: 1078 }],
    name: 'Friedrichshagen',
    region: 'U',
    slug: 'friedrichshagen',
  },
  {
    ids: [{ id: 1346 }],
    name: 'Friedrichshof',
    region: 'U',
    slug: 'friedrichshof',
  },
  {
    ids: [{ id: 1079 }],
    name: 'Gegensee',
    region: 'U',
    slug: 'gegensee',
  },
  {
    ids: [{ id: 1717 }],
    name: 'Gehege (zu Friedberg)',
    region: 'U',
    slug: 'gehege-zu-friedberg)',
  },
  {
    ids: [{ id: 1347 }],
    name: 'Gehege (zu Viereck)',
    region: 'U',
    slug: 'gehege-zu-viereck)',
  },
  {
    ids: [{ id: 1348 }],
    name: 'Gehren',
    region: 'U',
    slug: 'gehren',
  },
  {
    ids: [{ id: 1349 }],
    name: 'Gellin',
    region: 'U',
    slug: 'gellin',
  },
  {
    ids: [{ id: 1350 }],
    name: 'Glantzhof',
    region: 'U',
    slug: 'glantzhof',
  },
  {
    ids: [{ id: 1351 }],
    name: 'Glashütte',
    region: 'U',
    slug: 'glashuette',
  },
  {
    ids: [{ id: 1352 }],
    name: 'Glasow',
    region: 'U',
    slug: 'glasow',
  },
  {
    ids: [{ id: 1353 }],
    name: 'Gorkow',
    region: 'U',
    slug: 'gorkow',
  },
  {
    ids: [{ id: 1080 }],
    name: 'Grambin',
    region: 'U',
    slug: 'grambin',
  },
  {
    ids: [{ id: 1354 }],
    name: 'Grambow',
    region: 'U',
    slug: 'grambow',
  },
  {
    ids: [{ id: 1355 }],
    name: 'Grenzdorf',
    region: 'U',
    slug: 'grenzdorf',
  },
  {
    ids: [{ id: 1356 }],
    name: 'Groß Luckow',
    region: 'U',
    slug: 'gross-luckow',
  },
  {
    ids: [{ id: 1357 }],
    name: 'Groß Spiegelberg',
    region: 'U',
    slug: 'gross-spiegelberg',
  },
  {
    ids: [{ id: 1358 }],
    name: 'Grünhof',
    region: 'U',
    slug: 'gruenhof',
  },
  {
    ids: [{ id: 1359 }],
    name: 'Grünz',
    region: 'U',
    slug: 'gruenz',
  },
  {
    ids: [{ id: 1081 }],
    name: 'Gumnitz',
    region: 'U',
    slug: 'gumnitz',
  },
  {
    ids: [{ id: 1082 }],
    name: 'Hammer',
    region: 'U',
    slug: 'hammer',
  },
  {
    ids: [{ id: 1360 }],
    name: 'Heidemühle',
    region: 'U',
    slug: 'heidemuehle',
  },
  {
    ids: [{ id: 1083 }],
    name: 'Heinrichshof',
    region: 'U',
    slug: 'heinrichshof',
  },
  {
    ids: [{ id: 1084 }],
    name: 'Heinrichsruh',
    region: 'U',
    slug: 'heinrichsruh',
  },
  {
    ids: [{ id: 1085 }],
    name: 'Heinrichswalde',
    region: 'U',
    slug: 'heinrichswalde',
  },
  {
    ids: [{ id: 1361 }],
    name: 'Hinterfelde',
    region: 'U',
    slug: 'hinterfelde',
  },
  {
    ids: [{ id: 1086 }],
    name: 'Hintersee',
    region: 'U',
    slug: 'hintersee',
  },
  {
    ids: [{ id: 1362 }],
    name: 'Hohenfelde',
    region: 'U',
    slug: 'hohenfelde',
  },
  {
    ids: [{ id: 1363 }],
    name: 'Hohenholz',
    region: 'U',
    slug: 'hohenholz',
  },
  {
    ids: [{ id: 1087 }],
    name: 'Hoppenwalde',
    region: 'U',
    slug: 'hoppenwalde',
  },
  {
    ids: [{ id: 1088 }],
    name: 'Jatznick',
    region: 'U',
    slug: 'jatznick',
  },
  {
    ids: [{ id: 1364 }],
    name: 'Karlsburg',
    region: 'U',
    slug: 'karlsburg',
  },
  {
    ids: [{ id: 1365 }],
    name: 'Karlsfelde',
    region: 'U',
    slug: 'karlsfelde',
  },
  {
    ids: [{ id: 1366 }],
    name: 'Karlsruh',
    region: 'U',
    slug: 'karlsruh',
  },
  {
    ids: [{ id: 1367 }],
    name: 'Kirchenfeld',
    region: 'U',
    slug: 'kirchenfeld',
  },
  {
    ids: [{ id: 1368 }],
    name: 'Klein Luckow',
    region: 'U',
    slug: 'klein-luckow',
  },
  {
    ids: [{ id: 1369 }],
    name: 'Klepelshagen',
    region: 'U',
    slug: 'klepelshagen',
  },
  {
    ids: [{ id: 1370 }],
    name: 'Koblentz',
    region: 'U',
    slug: 'koblentz',
  },
  {
    ids: [{ id: 1371 }],
    name: 'Köhnshof',
    region: 'U',
    slug: 'koehnshof',
  },
  {
    ids: [{ id: 1372 }],
    name: 'Krackow',
    region: 'U',
    slug: 'krackow',
  },
  {
    ids: [{ id: 1373 }],
    name: 'Krugsdorf',
    region: 'U',
    slug: 'krugsdorf',
  },
  {
    ids: [{ id: 1374 }],
    name: 'Krugsdorfer Damm',
    region: 'U',
    slug: 'krugsdorfer-damm',
  },
  {
    ids: [{ id: 1375 }],
    name: 'Kuhlmorgen',
    region: 'U',
    slug: 'kuhlmorgen',
  },
  {
    ids: [{ id: 1376 }],
    name: 'Kyritz',
    region: 'U',
    slug: 'kyritz',
  },
  {
    ids: [{ id: 1377 }],
    name: 'Ladenthin',
    region: 'U',
    slug: 'ladenthin',
  },
  {
    ids: [{ id: 1378 }],
    name: 'Lauenhagen',
    region: 'U',
    slug: 'lauenhagen',
  },
  {
    ids: [{ id: 1379 }],
    name: 'Lebehn',
    region: 'U',
    slug: 'lebehn',
  },
  {
    ids: [{ id: 1091 }],
    name: 'Leopoldshagen',
    region: 'U',
    slug: 'leopoldshagen',
  },
  {
    ids: [{ id: 1092 }],
    name: 'Liepe (Hammer a. d. Uecker)',
    region: 'U',
    slug: 'liepe_hammer-a-d-uecker',
  },
  {
    ids: [{ id: 1093 }],
    name: 'Liepgarten',
    region: 'U',
    slug: 'liepgarten',
  },
  {
    ids: [{ id: 1380 }],
    name: 'Linchenshöh',
    region: 'U',
    slug: 'linchenshoeh',
  },
  {
    ids: [{ id: 1381 }],
    name: 'Linken',
    region: 'U',
    slug: 'linken',
  },
  {
    ids: [{ id: 1382 }],
    name: 'Löcknitz',
    region: 'U',
    slug: 'loecknitz',
  },
  {
    ids: [{ id: 1094 }],
    name: 'Louisenhof',
    region: 'U',
    slug: 'louisenhof',
  },
  {
    ids: [{ id: 1414 }],
    name: 'Louisfelde',
    region: 'U',
    slug: 'louisfelde',
  },
  {
    ids: [{ id: 1095 }],
    name: 'Lübs',
    region: 'U',
    slug: 'luebs',
  },
  {
    ids: [{ id: 1096 }],
    name: 'Luckow',
    region: 'U',
    slug: 'luckow',
  },
  {
    ids: [{ id: 1097 }],
    name: 'Ludwigshof',
    region: 'U',
    slug: 'ludwigshof',
  },
  {
    ids: [{ id: 1415 }],
    name: 'Ludwigsthal',
    region: 'U',
    slug: 'ludwigsthal',
  },
  {
    ids: [{ id: 1416 }],
    name: 'Luisenburg',
    region: 'U',
    slug: 'luisenburg',
  },
  {
    ids: [{ id: 1417 }],
    name: 'Lünschen Berge',
    region: 'U',
    slug: 'luenschen-berge',
  },
  {
    ids: [{ id: 1098 }],
    name: 'Mariawerth',
    region: 'U',
    slug: 'mariawerth',
  },
  {
    ids: [{ id: 1418 }],
    name: 'Marienfelde',
    region: 'U',
    slug: 'marienfelde',
  },
  {
    ids: [{ id: 1419 }],
    name: 'Marienhof',
    region: 'U',
    slug: 'marienhof',
  },
  {
    ids: [{ id: 1420 }],
    name: 'Marienthal',
    region: 'U',
    slug: 'marienthal',
  },
  {
    ids: [{ id: 1099 }],
    name: 'Meiersberg',
    region: 'U',
    slug: 'meiersberg',
  },
  {
    ids: [{ id: 1421 }],
    name: 'Mewegen',
    region: 'U',
    slug: 'mewegen',
  },
  {
    ids: [{ id: 1100 }],
    name: 'Mittagsberg',
    region: 'U',
    slug: 'mittagsberg',
  },
  {
    ids: [{ id: 1101 }],
    name: 'Mönkebude',
    region: 'U',
    slug: 'moenkebude',
  },
  {
    ids: [{ id: 1422 }],
    name: 'Muchowshof',
    region: 'U',
    slug: 'muchowshof',
  },
  {
    ids: [{ id: 1102 }],
    name: 'Müggenburg',
    region: 'U',
    slug: 'mueggenburg',
  },
  {
    ids: [{ id: 1103 }],
    name: 'Mühlenhof',
    region: 'U',
    slug: 'muehlenhof',
  },
  {
    ids: [{ id: 1423 }],
    name: 'Nadrensee',
    region: 'U',
    slug: 'nadrensee',
  },
  {
    ids: [{ id: 1424 }],
    name: 'Neu Polzow',
    region: 'U',
    slug: 'neu-polzow',
  },
  {
    ids: [{ id: 1425 }],
    name: 'Neu Stolzenburg',
    region: 'U',
    slug: 'neu-stolzenburg',
  },
  {
    ids: [{ id: 1426 }],
    name: 'Neu-Grambow',
    region: 'U',
    slug: 'neu-grambow',
  },
  {
    ids: [{ id: 1427 }],
    name: 'Neuensund',
    region: 'U',
    slug: 'neuensund',
  },
  {
    ids: [{ id: 1428 }],
    name: 'Neuhof',
    region: 'U',
    slug: 'neuhof',
  },
  {
    ids: [{ id: 1429 }],
    name: 'Nieden',
    region: 'U',
    slug: 'nieden',
  },
  {
    ids: [{ id: 1430 }],
    name: 'Ottilienau',
    region: 'U',
    slug: 'ottilienau',
  },
  {
    ids: [{ id: 1431 }],
    name: 'Pampow',
    region: 'U',
    slug: 'pampow',
  },
  {
    ids: [{ id: 1432 }],
    name: 'Papenbeck',
    region: 'U',
    slug: 'papenbeck',
  },
  {
    ids: [{ id: 1433 }],
    name: 'Papendorf',
    region: 'U',
    slug: 'papendorf',
  },
  {
    ids: [{ id: 1434 }],
    name: 'Papendorf Ausbau',
    region: 'U',
    slug: 'papendorf-ausbau',
  },
  {
    ids: [{ id: 1435 }],
    name: 'Papendorfer Chaussee',
    region: 'U',
    slug: 'papendorfer-chaussee',
  },
  {
    ids: [{ id: 1436 }],
    name: 'Pasewalk',
    region: 'U',
    slug: 'pasewalk',
  },
  {
    ids: [{ id: 1590 }],
    name: 'Penkun',
    region: 'U',
    slug: 'penkun',
  },
  {
    ids: [{ id: 1617 }],
    name: 'Peterswalde',
    region: 'U',
    slug: 'peterswalde',
  },
  {
    ids: [{ id: 1618 }],
    name: 'Plöwen',
    region: 'U',
    slug: 'ploewen',
  },
  {
    ids: [{ id: 1619 }],
    name: 'Polzow',
    region: 'U',
    slug: 'polzow',
  },
  {
    ids: [{ id: 1620 }],
    name: 'Pomellen',
    region: 'U',
    slug: 'pomellen',
  },
  {
    ids: [{ id: 1621 }],
    name: 'Radewitz',
    region: 'U',
    slug: 'radewitz',
  },
  {
    ids: [{ id: 1622 }],
    name: 'Ramin',
    region: 'U',
    slug: 'ramin',
  },
  {
    ids: [{ id: 1623 }],
    name: 'Ravensmühle',
    region: 'U',
    slug: 'ravensmuehle',
  },
  {
    ids: [{ id: 1624 }],
    name: 'Remelkoppel',
    region: 'U',
    slug: 'remelkoppel',
  },
  {
    ids: [{ id: 1625 }],
    name: 'Retzin',
    region: 'U',
    slug: 'retzin',
  },
  {
    ids: [{ id: 1626 }],
    name: 'Riesenbrück',
    region: 'U',
    slug: 'riesenbrueck',
  },
  {
    ids: [{ id: 1104 }],
    name: 'Rieth',
    region: 'U',
    slug: 'rieth',
  },
  {
    ids: [{ id: 1105 }],
    name: 'Rochow',
    region: 'U',
    slug: 'rochow',
  },
  {
    ids: [{ id: 1627 }],
    name: 'Rödershorst',
    region: 'U',
    slug: 'roedershorst',
  },
  {
    ids: [{ id: 1628 }],
    name: 'Roggow',
    region: 'U',
    slug: 'roggow',
  },
  {
    ids: [{ id: 1629 }],
    name: 'Rollwitz',
    region: 'U',
    slug: 'rollwitz',
  },
  {
    ids: [{ id: 1630 }],
    name: 'Rosenthal',
    region: 'U',
    slug: 'rosenthal',
  },
  {
    ids: [{ id: 1631 }],
    name: 'Rossow',
    region: 'U',
    slug: 'rossow',
  },
  {
    ids: [{ id: 1106 }],
    name: 'Rothemühl',
    region: 'U',
    slug: 'rothemuehl',
  },
  {
    ids: [{ id: 1632 }],
    name: 'Rothenburg',
    region: 'U',
    slug: 'rothenburg',
  },
  {
    ids: [{ id: 1633 }],
    name: 'Rothenklempenow',
    region: 'U',
    slug: 'rothenklempenow',
  },
  {
    ids: [{ id: 1634 }],
    name: 'Sandförde',
    region: 'U',
    slug: 'sandfoerde',
  },
  {
    ids: [{ id: 1635 }],
    name: 'Sandkrug',
    region: 'U',
    slug: 'sandkrug',
  },
  {
    ids: [{ id: 1636 }],
    name: 'Schmagerow',
    region: 'U',
    slug: 'schmagerow',
  },
  {
    ids: [{ id: 1637 }],
    name: 'Schmarsow',
    region: 'U',
    slug: 'schmarsow',
  },
  {
    ids: [{ id: 1638 }],
    name: 'Schmarsow Ausbau',
    region: 'U',
    slug: 'schmarsow-ausbau',
  },
  {
    ids: [{ id: 1639 }],
    name: 'Schneidershof',
    region: 'U',
    slug: 'schneidershof',
  },
  {
    ids: [{ id: 1640 }],
    name: 'Schönburg',
    region: 'U',
    slug: 'schoenburg',
  },
  {
    ids: [{ id: 1641 }],
    name: 'Schönwalde',
    region: 'U',
    slug: 'schoenwalde',
  },
  {
    ids: [{ id: 1642 }],
    name: 'Schuckmannshöhe',
    region: 'U',
    slug: 'schuckmannshoehe',
  },
  {
    ids: [{ id: 1643 }],
    name: 'Schwarzensee',
    region: 'U',
    slug: 'schwarzensee',
  },
  {
    ids: [{ id: 1644 }],
    name: 'Schwarzensee Siedlung',
    region: 'U',
    slug: 'schwarzensee-siedlung',
  },
  {
    ids: [{ id: 1645 }],
    name: 'Schwennenz',
    region: 'U',
    slug: 'schwennenz',
  },
  {
    ids: [{ id: 1647 }],
    name: 'Sommersdorf',
    region: 'U',
    slug: 'sommersdorf',
  },
  {
    ids: [{ id: 1648 }],
    name: 'Sonnenberg',
    region: 'U',
    slug: 'sonnenberg',
  },
  {
    ids: [{ id: 1107 }],
    name: 'Sprengersfelde',
    region: 'U',
    slug: 'sprengersfelde',
  },
  {
    ids: [{ id: 1649 }],
    name: 'Stallberg',
    region: 'U',
    slug: 'stallberg',
  },
  {
    ids: [{ id: 1650 }],
    name: 'Starkshof',
    region: 'U',
    slug: 'starkshof',
  },
  {
    ids: [{ id: 1651 }],
    name: 'Steinbrink',
    region: 'U',
    slug: 'steinbrink',
  },
  {
    ids: [{ id: 1652 }],
    name: 'Stiftshof',
    region: 'U',
    slug: 'stiftshof',
  },
  {
    ids: [{ id: 1653 }],
    name: 'Stolzenburg',
    region: 'U',
    slug: 'stolzenburg',
  },
  {
    ids: [{ id: 1654 }],
    name: 'Storkow',
    region: 'U',
    slug: 'storkow',
  },
  {
    ids: [{ id: 1655 }],
    name: 'Strasburg',
    redion: 'U',
    slug: 'strasburg',
  },
  {
    ids: [{ id: 1703 }],
    name: 'Streithof',
    region: 'U',
    slug: 'streithof',
  },
  {
    ids: [{ id: 1704 }],
    name: 'Theerofen',
    region: 'U',
    slug: 'theerofen',
  },
  {
    ids: [{ id: 1108 }],
    name: 'Torgelow',
    redion: 'U',
    slug: 'torgelow',
  },
  {
    ids: [{ id: 1191 }],
    name: 'Torgelow-Drögeheide',
    region: 'U',
    slug: 'torgelow-droegeheide',
  },
  {
    ids: [{ id: 1209 }],
    name: 'Torgelow-Spechtberg',
    region: 'U',
    slug: 'torgelow-spechtberg',
  },
  {
    ids: [{ id: 1224 }],
    name: 'Torgelow/Holl-Schlossberg',
    region: 'U',
    slug: 'torgelow-holl-schlossberg',
  },
  {
    ids: [{ id: 1225 }],
    name: 'Torgelow/Holl.',
    region: 'U',
    slug: 'torgelow-holl.',
  },
  {
    ids: [{ id: 1226 }],
    name: 'Ueckermünde',
    redion: 'U',
    slug: 'ueckermuende',
  },
  {
    ids: [{ id: 1705 }],
    name: 'Uhlenkrug',
    region: 'U',
    slug: 'uhlenkrug',
  },
  {
    ids: [{ id: 1706 }],
    name: 'Viereck',
    region: 'U',
    slug: 'viereck',
  },
  {
    ids: [{ id: 1707 }],
    name: 'Viereck/ETS',
    region: 'U',
    slug: 'viereck-ets',
  },
  {
    ids: [{ id: 1317 }],
    name: 'Vogelsang',
    region: 'U',
    slug: 'vogelsang',
  },
  {
    ids: [{ id: 1708 }],
    name: 'Waldeshöhe',
    region: 'U',
    slug: 'waldeshoehe',
  },
  {
    ids: [{ id: 1318 }],
    name: 'Warsin',
    region: 'U',
    slug: 'warsin',
  },
  {
    ids: [{ id: 1709 }],
    name: 'Wetzenow',
    region: 'U',
    slug: 'wetzenow',
  },
  {
    ids: [{ id: 1319 }],
    name: 'Wietstock',
    region: 'U',
    slug: 'wietstock',
  },
  {
    ids: [{ id: 1721 }],
    name: 'Wilhelmsburg',
    region: 'U',
    slug: 'wilhelmsburg',
  },
  {
    ids: [{ id: 1320 }],
    name: 'Wilhelmsburg bei Torgelow',
    region: 'U',
    slug: 'wilhelmsburg-bei-torgelow',
  },
  {
    ids: [{ id: 1710 }],
    name: 'Wilhelmshof',
    region: 'U',
    slug: 'wilhelmshof',
  },
  {
    ids: [{ id: 1711 }],
    name: 'Wilhelmslust',
    region: 'U',
    slug: 'wilhelmslust',
  },
  {
    ids: [{ id: 1712 }],
    name: 'Wollin',
    region: 'U',
    slug: 'wollin',
  },
  {
    ids: [{ id: 1713 }],
    name: 'Zerrenthin',
    region: 'U',
    slug: 'zerrenthin',
  },
  {
    ids: [{ id: 1714 }],
    name: 'Ziegelhausen',
    region: 'U',
    slug: 'ziegelhausen',
  },
  {
    ids: [{ id: 1715 }],
    name: 'Zimmermannsmühle',
    region: 'U',
    slug: 'zimmermannsmuehle',
  },
  {
    ids: [{ id: 1716 }],
    name: 'Züsedom',
    region: 'U',
    slug: 'zuesedom',
  },
];

const getVillage = slug => {
  return findWhere(villages, { slug: slug });
};

export default getVillage;
